/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import com.project.mobileshop.controller.BatchController;
import com.project.mobileshop.controller.GRNController;
import com.project.mobileshop.controller.ModelController;
import com.project.mobileshop.controller.SupplierController;
import com.project.mobileshop.core.dto.BatchDTO;
import com.project.mobileshop.core.dto.GRNDTO;
import com.project.mobileshop.core.dto.ModelDTO;
import com.project.mobileshop.core.dto.SupplierDTO;
import com.project.mobileshop.db.DBConnection;
import com.project.mobileshop.idgeneretor.IDGenerator;
import com.project.mobileshop.util.Validation;
import com.project.mobileshop.view.AddBatchDialog;
import com.project.mobileshop.view.AddGRNItemDialog;
import com.project.mobileshop.view.AddGRNItemMessageDialog;
import com.project.mobileshop.view.JoptionMessageDialog;
import com.project.mobileshop.view.MainPage;
import com.project.mobileshop.view.ViewGRNs;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Font;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author Janitha Dhananjaya
 */
@Report("com.project.mobileshop.report")
public class AddGRN extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private static String newBatchNo;

    /**
     * Creates new form AddGRN
     */
    public AddGRN() {
        initComponents();
        LoadSupplierIDs();
        generateGRNNo();
        LoadCurrentDate();
        dtm = (DefaultTableModel) GRNtable.getModel();
        DisabledDates();
    }

    private void DisabledDates() {
        Date date = new Date();
        GRN_Date.getMonthView().setUpperBound(date);
    }

    public void clearAllText() {
        brandTxt.setText("");
        modelNameTxt.setText("");
        modelNoTxt.setText("");
        unitPriceTxt.setText("");
        yearTxt.setText("");
        deliverdQtyTxt.setText("");
        warrentyTxt.setText("");
        batchNoComboBox.removeAllItems();
        totalAmountTxt.setText("");
    }

    public void generateGRNNo() {
        try {
            GRNnoTxt.setText(IDGenerator.getNewID("grn", "GRNno", "G"));
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void LoadSupplierIDs() {
        try {
            ArrayList<SupplierDTO> allSuppliersIDs = SupplierController.getAllSuppliers();
            if (allSuppliersIDs != null) {
                for (SupplierDTO s : allSuppliersIDs) {
                    supplierIdCombo.addItem(s.getSupplierId());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRNPanel = new org.jdesktop.swingx.JXPanel();
        title_lbl = new org.jdesktop.swingx.JXLabel();
        GRN_ID_Lbl = new org.jdesktop.swingx.JXLabel();
        GRNnoTxt = new org.jdesktop.swingx.JXTextField();
        Date_Lbl = new org.jdesktop.swingx.JXLabel();
        GRN_Date = new org.jdesktop.swingx.JXDatePicker();
        buttonPanel = new org.jdesktop.swingx.JXPanel();
        GRNTableScroll = new javax.swing.JScrollPane();
        GRNtable = new org.jdesktop.swingx.JXTable();
        addGRNbt = new org.jdesktop.swingx.JXLabel();
        totalAmountTxt = new org.jdesktop.swingx.JXTextField();
        companyLbl = new org.jdesktop.swingx.JXLabel();
        supplierNmaeLbl = new org.jdesktop.swingx.JXLabel();
        supplirIdLbl = new org.jdesktop.swingx.JXLabel();
        CompanyTxt = new org.jdesktop.swingx.JXTextField();
        supplierNameTxt = new org.jdesktop.swingx.JXTextField();
        supplierIdCombo = new org.jdesktop.swingx.JXComboBox();
        GRNdtailPanel = new org.jdesktop.swingx.JXLabel();
        viewAllBtn = new org.jdesktop.swingx.JXLabel();
        BtnSave = new org.jdesktop.swingx.JXLabel();
        BtnAddItem = new org.jdesktop.swingx.JXLabel();
        modelNameTxt = new org.jdesktop.swingx.JXTextField();
        modelNameLbl = new org.jdesktop.swingx.JXLabel();
        brandTxt = new org.jdesktop.swingx.JXTextField();
        brandLbl = new org.jdesktop.swingx.JXLabel();
        modelNoTxt = new org.jdesktop.swingx.JXTextField();
        modelNoLbl = new org.jdesktop.swingx.JXLabel();
        yearTxt = new org.jdesktop.swingx.JXTextField();
        totalAmountLbl = new org.jdesktop.swingx.JXLabel();
        unitPricelbl = new org.jdesktop.swingx.JXLabel();
        unitPriceTxt = new org.jdesktop.swingx.JXTextField();
        batchNoLbl = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        printBtn = new org.jdesktop.swingx.JXLabel();
        batchNoComboBox = new org.jdesktop.swingx.JXComboBox();
        deliverdQtyTxt = new org.jdesktop.swingx.JXTextField();
        BtnRemove = new org.jdesktop.swingx.JXLabel();
        deliQtyLbl = new org.jdesktop.swingx.JXLabel();
        companyWarrentLbl = new org.jdesktop.swingx.JXLabel();
        warrentyTxt = new org.jdesktop.swingx.JXTextField();
        addBtn = new org.jdesktop.swingx.JXLabel();
        itemDetailboaderLbl = new org.jdesktop.swingx.JXLabel();
        yearLbl1 = new org.jdesktop.swingx.JXLabel();
        newBatchBtn = new org.jdesktop.swingx.JXLabel();
        itemDetailboaderLbl1 = new org.jdesktop.swingx.JXLabel();
        newBt = new org.jdesktop.swingx.JXLabel();
        CustomPanel = new org.jdesktop.swingx.JXPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRNPanel.setBackground(new java.awt.Color(255, 255, 255));
        GRNPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lbl.setText("Good Recieved Note");
        title_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        GRNPanel.add(title_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 390, 50));

        GRN_ID_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GRN_ID_Lbl.setText("GRN No");
        GRN_ID_Lbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(GRN_ID_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        GRNnoTxt.setEditable(false);
        GRNnoTxt.setBackground(new java.awt.Color(248, 248, 248));
        GRNnoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        GRNnoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNPanel.add(GRNnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 190, 30));

        Date_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date_Lbl.setText("Date");
        Date_Lbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(Date_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 80, 30));

        GRN_Date.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRN_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRN_DateActionPerformed(evt);
            }
        });
        GRNPanel.add(GRN_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 190, 30));

        buttonPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRNtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        GRNtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model No", "Model Name", "Brand", "Delivered Qty", "Unit Price", "Warrenty Period", "Year", "Amount", "Batch No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GRNtable.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNtable.setGridColor(new java.awt.Color(0, 102, 102));
        GRNTableScroll.setViewportView(GRNtable);

        buttonPanel.add(GRNTableScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 250));

        addGRNbt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addGRNbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Add GRN.png"))); // NOI18N
        addGRNbt.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        addGRNbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addGRNbtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addGRNbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addGRNbtMouseExited(evt);
            }
        });
        buttonPanel.add(addGRNbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 190, 30));

        GRNPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 780, 250));

        totalAmountTxt.setEditable(false);
        totalAmountTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totalAmountTxt.setForeground(new java.awt.Color(8, 101, 101));
        totalAmountTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        totalAmountTxt.setOpaque(false);
        GRNPanel.add(totalAmountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 180, 40));

        companyLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyLbl.setText("Company");
        companyLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(companyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 110, 30));

        supplierNmaeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierNmaeLbl.setText("Supplier Name");
        supplierNmaeLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(supplierNmaeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 30));

        supplirIdLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplirIdLbl.setText("Supplier ID");
        supplirIdLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(supplirIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 120, 30));

        CompanyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        CompanyTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        CompanyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyTxtActionPerformed(evt);
            }
        });
        GRNPanel.add(CompanyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 190, 30));

        supplierNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supplierNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supplierNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtActionPerformed(evt);
            }
        });
        supplierNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                supplierNameTxtKeyTyped(evt);
            }
        });
        GRNPanel.add(supplierNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 190, 30));

        supplierIdCombo.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supplierIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supplierIdComboItemStateChanged(evt);
            }
        });
        supplierIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIdComboActionPerformed(evt);
            }
        });
        GRNPanel.add(supplierIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 190, 30));

        GRNdtailPanel.setBackground(new java.awt.Color(255, 255, 255));
        GRNdtailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81)), "GRN Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gadugi", 1, 12), new java.awt.Color(23, 114, 81))); // NOI18N
        GRNdtailPanel.setOpaque(true);
        GRNPanel.add(GRNdtailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1000, 110));

        viewAllBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(255, 255, 0), null, null));
        viewAllBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAllBtn.setText("View All");
        viewAllBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        viewAllBtn.setOpaque(true);
        viewAllBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllBtnMouseExited(evt);
            }
        });
        GRNPanel.add(viewAllBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 150, 30));

        BtnSave.setBackground(new java.awt.Color(255, 255, 255));
        BtnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSave.setText("Save");
        BtnSave.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        BtnSave.setOpaque(true);
        BtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSaveMouseExited(evt);
            }
        });
        GRNPanel.add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 110, 40));

        BtnAddItem.setBackground(new java.awt.Color(255, 255, 255));
        BtnAddItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnAddItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAddItem.setText("Add Items");
        BtnAddItem.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        BtnAddItem.setOpaque(true);
        BtnAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAddItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAddItemMouseExited(evt);
            }
        });
        GRNPanel.add(BtnAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 110, 40));

        modelNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameTxtActionPerformed(evt);
            }
        });
        GRNPanel.add(modelNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 180, 30));

        modelNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelNameLbl.setText("Model Name");
        modelNameLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(modelNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 90, 30));

        brandTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        brandTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        brandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTxtActionPerformed(evt);
            }
        });
        brandTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brandTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brandTxtKeyTyped(evt);
            }
        });
        GRNPanel.add(brandTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 180, 30));

        brandLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brandLbl.setText("Brand");
        brandLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(brandLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 30));

        modelNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxtActionPerformed(evt);
            }
        });
        GRNPanel.add(modelNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 180, 30));

        modelNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelNoLbl.setText("Model No");
        modelNoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(modelNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 80, 30));

        yearTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        yearTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        yearTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTxtActionPerformed(evt);
            }
        });
        yearTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearTxtKeyTyped(evt);
            }
        });
        GRNPanel.add(yearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 180, 30));

        totalAmountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmountLbl.setText("Total Amount");
        totalAmountLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNPanel.add(totalAmountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 140, 40));

        unitPricelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unitPricelbl.setText("Unit Price");
        unitPricelbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(unitPricelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, 30));

        unitPriceTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        unitPriceTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        unitPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitPriceTxtActionPerformed(evt);
            }
        });
        unitPriceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitPriceTxtKeyTyped(evt);
            }
        });
        GRNPanel.add(unitPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, 30));

        batchNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batchNoLbl.setText("Batch No");
        batchNoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(batchNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 120, 30));

        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("Months");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, 30));

        printBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        printBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printBtn.setText("Print GRN");
        printBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        printBtn.setOpaque(true);
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printBtnMouseExited(evt);
            }
        });
        GRNPanel.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 594, 110, 40));

        batchNoComboBox.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        batchNoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNoComboBoxActionPerformed(evt);
            }
        });
        GRNPanel.add(batchNoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 180, 30));

        deliverdQtyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        deliverdQtyTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        deliverdQtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverdQtyTxtActionPerformed(evt);
            }
        });
        deliverdQtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deliverdQtyTxtKeyTyped(evt);
            }
        });
        GRNPanel.add(deliverdQtyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 180, 30));

        BtnRemove.setBackground(new java.awt.Color(255, 255, 255));
        BtnRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnRemove.setText("Remove");
        BtnRemove.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        BtnRemove.setOpaque(true);
        BtnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRemoveMouseExited(evt);
            }
        });
        GRNPanel.add(BtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 110, 40));

        deliQtyLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliQtyLbl.setText("Delivered Qty");
        deliQtyLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(deliQtyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 120, 30));

        companyWarrentLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyWarrentLbl.setText("Warrenty");
        companyWarrentLbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(companyWarrentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, 30));

        warrentyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        warrentyTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        warrentyTxt.setOpaque(false);
        warrentyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrentyTxtActionPerformed(evt);
            }
        });
        warrentyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                warrentyTxtKeyTyped(evt);
            }
        });
        GRNPanel.add(warrentyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, 30));

        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn.setText("ADD");
        addBtn.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        addBtn.setOpaque(true);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });
        GRNPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 80, 30));

        itemDetailboaderLbl.setBackground(new java.awt.Color(255, 255, 255));
        itemDetailboaderLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81)));
        itemDetailboaderLbl.setOpaque(true);
        GRNPanel.add(itemDetailboaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 180, 250));

        yearLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLbl1.setText("Year");
        yearLbl1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GRNPanel.add(yearLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 80, 30));

        newBatchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81)));
        newBatchBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newBatchBtn.setText("All");
        newBatchBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        newBatchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBatchBtnMouseClicked(evt);
            }
        });
        GRNPanel.add(newBatchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 40, 30));

        itemDetailboaderLbl1.setBackground(new java.awt.Color(255, 255, 255));
        itemDetailboaderLbl1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81)), "Item Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gadugi", 1, 12), new java.awt.Color(23, 114, 81))); // NOI18N
        itemDetailboaderLbl1.setOpaque(true);
        GRNPanel.add(itemDetailboaderLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1000, 170));

        newBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newBt.setText("NEW");
        newBt.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        newBt.setOpaque(true);
        newBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newBtMouseExited(evt);
            }
        });
        GRNPanel.add(newBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 80, 30));

        CustomPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CustomPanelLayout = new javax.swing.GroupLayout(CustomPanel);
        CustomPanel.setLayout(CustomPanelLayout);
        CustomPanelLayout.setHorizontalGroup(
            CustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CustomPanelLayout.setVerticalGroup(
            CustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        GRNPanel.add(CustomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1060, 610));

        add(GRNPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void GRN_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRN_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRN_DateActionPerformed

    private void CompanyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyTxtActionPerformed

    private void supplierNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTxtActionPerformed

    private void viewAllBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBtnMouseEntered
        viewAllBtn.setBackground(new Color(23, 114, 81));
        viewAllBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_viewAllBtnMouseEntered

    private void viewAllBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBtnMouseExited
        viewAllBtn.setBackground(new Color(255, 255, 255));
        viewAllBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_viewAllBtnMouseExited

    private void newBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtMouseEntered
        newBt.setBackground(new Color(23, 114, 81));
        newBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_newBtMouseEntered

    private void newBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtMouseExited
        newBt.setBackground(new Color(255, 255, 255));
        newBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_newBtMouseExited

    private void addGRNbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGRNbtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addGRNbtMouseEntered

    private void addGRNbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGRNbtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addGRNbtMouseExited

    private void viewAllBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBtnMouseClicked
        ViewGRNs viewGRN = new ViewGRNs(null, true);
        viewGRN.setVisible(true);

    }//GEN-LAST:event_viewAllBtnMouseClicked

    private void supplierIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supplierIdComboItemStateChanged
        String supplierId = supplierIdCombo.getSelectedItem().toString();
        SupplierDTO supplierDTO = new SupplierDTO();
        supplierDTO.setSupplierId(supplierId);
        try {
            SupplierDTO searchSupplier = SupplierController.searchSupplier(supplierDTO);
            if (searchSupplier != null) {
                supplierNameTxt.setText(searchSupplier.getSupplierName());
                CompanyTxt.setText(searchSupplier.getCompany());
            }
        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supplierIdComboItemStateChanged

    private void supplierIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIdComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIdComboActionPerformed

    private void addGRNbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGRNbtMouseClicked

    }//GEN-LAST:event_addGRNbtMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked

        String brand = brandTxt.getText();
        String modelName = modelNameTxt.getText();
        String modelNo = modelNoTxt.getText();
        String GRNno = GRNnoTxt.getText();
        String warrenty = warrentyTxt.getText();
        String year = yearTxt.getText();
        String qty = deliverdQtyTxt.getText();
        String unitPrice = unitPriceTxt.getText();

        if (GRNno.isEmpty() || brand.isEmpty() || modelName.isEmpty() || modelNo.isEmpty() || warrenty.isEmpty() || year.isEmpty() || qty.isEmpty() || unitPrice.isEmpty() || (batchNoComboBox.getSelectedItem().toString().equals("No any Batch"))) {

            String content = "Please  fill All Text Fields";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        String batchNo = batchNoComboBox.getSelectedItem().toString();

        int deliveredQty = Integer.parseInt(deliverdQtyTxt.getText());
        double price = Double.parseDouble(unitPriceTxt.getText());
        int warrentyPeriod = Integer.parseInt(warrentyTxt.getText());
        double amount = price * deliveredQty;

        int index = 0;
        boolean isExist = false;

        for (int i = 0; i < GRNtable.getRowCount(); i++) {
            if (modelName.equals(GRNtable.getValueAt(i, 1).toString())) {
                isExist = true;
                index = i;
                break;

            }
        }

        if (isExist) {
            int oldQTy = Integer.parseInt(GRNtable.getValueAt(index, 3).toString());
            int newQty = oldQTy + deliveredQty;

            double oldAmount = Double.parseDouble(GRNtable.getValueAt(index, 7).toString());
            double newAmount = oldAmount + amount;

            dtm.setValueAt(newQty, index, 3);
            dtm.setValueAt(newAmount, index, 7);
            GRNTTotalAmount += amount;
            totalAmountTxt.setText(String.valueOf(GRNTTotalAmount));

        } else {
            addButton++;
            GRNTTotalAmount += amount;
            totalAmountTxt.setText(String.valueOf(GRNTTotalAmount));

            Object[] row = {modelNo, modelName, brand, deliveredQty, price, warrentyPeriod, year, amount, batchNo};
            dtm.addRow(row);
        }

        modelNameTxt.setText("");
        brandTxt.setText("");
        unitPriceTxt.setText("");
        warrentyTxt.setText("");
        modelNoTxt.setText("");
        deliverdQtyTxt.setText("");
        yearTxt.setText("");
        batchNoComboBox.removeAllItems();
        brandTxt.requestFocus();
        
        modelNoTxt.setEditable(true);


    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        addBtn.setBackground(new Color(23, 114, 81));
        addBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        addBtn.setBackground(new Color(255, 255, 255));
        addBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addBtnMouseExited

    private void BtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSaveMouseClicked
        if (GRNtable.getRowCount() == 0) {
            return;
        }

        saveBtn++;
        addBtClickCount++;

        String GRNId = GRNnoTxt.getText();
        String supplierId = supplierIdCombo.getSelectedItem().toString();
        Date grnDate = GRN_Date.getDate();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String GRNdate = date.format(grnDate);

        double totalAmount = Double.parseDouble(totalAmountTxt.getText());

        System.out.println("start");

        GRNDTO grnDTO = new GRNDTO(GRNId, supplierId, GRNdate, totalAmount);

        ArrayList<ModelDTO> modelList = new ArrayList<>();
        ArrayList<BatchDTO> batchList = new ArrayList<>();

        boolean batchExist = false;

        for (int i = 0; i < GRNtable.getRowCount(); i++) {
            ModelDTO modelDTO = new ModelDTO(
                    GRNtable.getValueAt(i, 2).toString(), GRNtable.getValueAt(i, 1).toString(),
                    GRNtable.getValueAt(i, 0).toString(), Integer.parseInt(GRNtable.getValueAt(i, 3).toString()),
                    Integer.parseInt(GRNtable.getValueAt(i, 5).toString()), Integer.parseInt(GRNtable.getValueAt(i, 6).toString()));

            BatchDTO batchDTO = new BatchDTO(
                    GRNtable.getValueAt(i, 8).toString(), GRNtable.getValueAt(i, 0).toString(), new BigDecimal(0), new BigDecimal(GRNtable.getValueAt(i, 4).toString()),
                    Integer.parseInt(GRNtable.getValueAt(i, 3).toString()), new BigDecimal(Double.parseDouble(GRNtable.getValueAt(i, 7).toString())));

            System.out.println("arraylist added data");

            modelList.add(modelDTO);
            batchList.add(batchDTO);
        }

        System.out.println("end for loop");

        try {
            boolean isaddGRN = GRNController.addGRN(grnDTO, modelList, batchList);

            System.out.println("Successfully adeded grn, model, batch");

            if (isaddGRN) {
                AddGRNItemMessageDialog addGRNItemMessageDialog = new AddGRNItemMessageDialog(null, true);
                addGRNItemMessageDialog.setVisible(true);
                clearAllText();
                GRNTTotalAmount = 0;
                BtnRemove.setEnabled(false);
                addBtn.setEnabled(false);

                BtnSave.setEnabled(false);

            } else {
                //JOptionPane.showMessageDialog(this, "GRN not added");
                String content = "GRN not added";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
                dialog.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtnSaveMouseClicked

    private void BtnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSaveMouseEntered
        BtnSave.setBackground(new Color(23, 114, 81));
        BtnSave.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BtnSaveMouseEntered

    private void BtnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSaveMouseExited
        BtnSave.setBackground(new Color(255, 255, 255));
        BtnSave.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_BtnSaveMouseExited

    private void BtnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRemoveMouseClicked
        if (GRNtable.getSelectedRow() == -1) {
            //JOptionPane.showMessageDialog(this, "Select a row");
            String content = "Select a row";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);

            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) GRNtable.getModel();

        int removeRow = GRNtable.getSelectedRow();
        double removeAmount = Double.parseDouble(GRNtable.getValueAt(removeRow, 7).toString());
        GRNTTotalAmount -= removeAmount;
        dtm.removeRow(removeRow);
        totalAmountTxt.setText(String.valueOf(GRNTTotalAmount));


    }//GEN-LAST:event_BtnRemoveMouseClicked

    private void BtnRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRemoveMouseEntered
        BtnRemove.setBackground(new Color(255, 14, 65));
        BtnRemove.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BtnRemoveMouseEntered

    private void BtnRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRemoveMouseExited
        BtnRemove.setBackground(new Color(255, 255, 255));
        BtnRemove.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_BtnRemoveMouseExited

    private void unitPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitPriceTxtActionPerformed

    }//GEN-LAST:event_unitPriceTxtActionPerformed

    private void BtnAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddItemMouseClicked

        if (saveBtn == 0) {
            String content = "Please Save GRN First";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }
        if (GRNtable.getSelectedRow() == -1) {
            String content = "Select a model in table";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        int selectedRow = GRNtable.getSelectedRow();
        System.out.println("selected Colum  " + selectedRow);

        ModelDTO modelDTO = new ModelDTO(
                GRNtable.getValueAt(selectedRow, 2).toString(),
                GRNtable.getValueAt(selectedRow, 1).toString(),
                GRNtable.getValueAt(selectedRow, 0).toString(),
                Integer.parseInt(GRNtable.getValueAt(selectedRow, 3).toString()),
                Integer.parseInt(GRNtable.getValueAt(selectedRow, 5).toString()),
                Integer.parseInt(GRNtable.getValueAt(selectedRow, 6).toString())
        );

        String GRNno = GRNnoTxt.getText();

        String batchNo = GRNtable.getValueAt(selectedRow, 8).toString();

        AddGRNItemDialog dialog = new AddGRNItemDialog(null, true);
        dialog.getModelData(modelDTO, GRNno, batchNo);
        dialog.setVisible(true);
        dtm.removeRow(selectedRow);


    }//GEN-LAST:event_BtnAddItemMouseClicked

    private void batchNoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNoComboBoxActionPerformed

    private void newBatchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBatchBtnMouseClicked
        String modelNo = modelNoTxt.getText();
        String modelName = modelNameTxt.getText();

        if (modelNo.trim().isEmpty() || modelName.trim().isEmpty()) {
            return;
        }

        AddBatchDialog dialog = new AddBatchDialog(null, true);
        try {
            dialog.LoadRelavantBatches(modelNo, modelName);

        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setVisible(true);
    }//GEN-LAST:event_newBatchBtnMouseClicked

    private void warrentyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrentyTxtActionPerformed
        yearTxt.requestFocus();
    }//GEN-LAST:event_warrentyTxtActionPerformed

    private void newBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtMouseClicked
        String brand = brandTxt.getText();
        String modelName = modelNameTxt.getText();
        String modelNo = modelNoTxt.getText();
        String unitprice = unitPriceTxt.getText();
        String year = yearTxt.getText();
        String deliveredQty = deliverdQtyTxt.getText();
        String warrenty = warrentyTxt.getText();

        if (addBtClickCount == 0 & (!(brand.isEmpty()) | !(modelName.isEmpty()) | !(modelNo.isEmpty()) | !(unitprice.isEmpty()) | !(year.isEmpty()) | !(deliveredQty.isEmpty()) | !(warrenty.isEmpty()))) {
            int result = JOptionPane.showConfirmDialog(this, "Do you sure to cancel this GRN ?", "Messge", JOptionPane.YES_NO_OPTION);
            System.out.println("Yes" + result);
            if (result == 0) {
                clearAllText();
            }
            return;
        }
    }//GEN-LAST:event_newBtMouseClicked

    private void brandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTxtActionPerformed
        modelNameTxt.requestFocus();
    }//GEN-LAST:event_brandTxtActionPerformed

    private void modelNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameTxtActionPerformed
        String modelName = modelNameTxt.getText();
        try {
            ModelDTO modelNo = ModelController.getModelDetails(modelName);
            if (modelNo != null) {
                modelNoTxt.setText(modelNo.getModelNo());
                warrentyTxt.requestFocus();
                modelNoTxt.setEditable(false);

            } else {
                modelNoTxt.requestFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_modelNameTxtActionPerformed

    private void modelNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxtActionPerformed
        warrentyTxt.requestFocus();
    }//GEN-LAST:event_modelNoTxtActionPerformed

    private void yearTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTxtActionPerformed
        deliverdQtyTxt.requestFocus();
    }//GEN-LAST:event_yearTxtActionPerformed

    private void deliverdQtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverdQtyTxtActionPerformed
        unitPriceTxt.requestFocus();
    }//GEN-LAST:event_deliverdQtyTxtActionPerformed

    private void warrentyTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_warrentyTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = warrentyTxt.getText();
        if (!Character.isDigit(keyChar) || IMEI.length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_warrentyTxtKeyTyped

    private void unitPriceTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitPriceTxtKeyTyped
        char keyChar = evt.getKeyChar();

        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }

        String dQty = deliverdQtyTxt.getText();
        String uPrice = unitPriceTxt.getText();
        String mNo = modelNoTxt.getText();

        if (dQty.trim().isEmpty() || uPrice.trim().isEmpty() || mNo.trim().isEmpty()) {
            return;
        }

        int deliveredQty = Integer.parseInt(deliverdQtyTxt.getText());
        double price = Double.parseDouble(unitPriceTxt.getText());

        double amount = price * deliveredQty;

        BatchDTO batchDTO = new BatchDTO();
        batchDTO.setModelNo(modelNoTxt.getText());
        batchDTO.setOriginalPrice(new BigDecimal(unitPriceTxt.getText()));

        try {
            Object batch = BatchController.getBatchs(batchDTO);
            batchNoComboBox.removeAllItems();
            if (batch != null) {
                batchNoComboBox.addItem(batch);
            }

        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class
                    .getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_unitPriceTxtKeyTyped

    private void yearTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String year = yearTxt.getText();
        if (!Character.isDigit(keyChar) || year.length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_yearTxtKeyTyped

    private void deliverdQtyTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deliverdQtyTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String ty = deliverdQtyTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_deliverdQtyTxtKeyTyped

    private void supplierNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameTxtKeyTyped
        Validation.name(supplierNameTxt);
    }//GEN-LAST:event_supplierNameTxtKeyTyped

    private void brandTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTxtKeyTyped

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked
        if (saveBtn == 0) {
            String content = "Save GRN First";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        JasperUtil.init(AddGRN.class);

        JasperReportsContext ctx = JasperUtil.getReportContext();

        try {
            JasperReport compiledReport = JasperUtil.getCompiledReport("GRN.jasper");

            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);

            HashMap<String, Object> reportParams = new HashMap<>();

            reportParams.put("grnno", GRNnoTxt.getText());

            Connection connection = DBConnection.getInstance().getConnection();
            JasperPrint filledReport = fillManager.fill(compiledReport, reportParams, connection);

            IJSEJasperViewer frmJSEJasperViewer = new IJSEJasperViewer(filledReport);
            frmJSEJasperViewer.setTitle("GRN Details Report");
            frmJSEJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJSEJasperViewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printBtnMouseClicked

    private void BtnAddItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddItemMouseEntered
        BtnAddItem.setBackground(new Color(23, 114, 81));
        BtnAddItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_BtnAddItemMouseEntered

    private void BtnAddItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddItemMouseExited
        BtnAddItem.setBackground(new Color(255, 255, 255));
        BtnAddItem.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_BtnAddItemMouseExited

    private void printBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseExited
        printBtn.setBackground(new Color(255, 255, 255));
        printBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_printBtnMouseExited

    private void printBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseEntered
        printBtn.setBackground(new Color(23, 114, 81));
        printBtn.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_printBtnMouseEntered

    private void brandTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandTxtKeyReleased
        String brand = brandTxt.getText();
        if(brand.length()<=1){
            return;
        }
        try {
            ModelDTO isExist = ModelController.FillBrandName(brand);
            if (isExist != null) {
                brandTxt.setText(isExist.getBrand());
            } else {
                brandTxt.setToolTipText("New Brand");
            }
        } catch (Exception ex) {
            Logger.getLogger(AddGRN.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_brandTxtKeyReleased

    public void getNewBatch(BatchDTO batchDTO) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel BtnAddItem;
    private org.jdesktop.swingx.JXLabel BtnRemove;
    private org.jdesktop.swingx.JXLabel BtnSave;
    private org.jdesktop.swingx.JXTextField CompanyTxt;
    private org.jdesktop.swingx.JXPanel CustomPanel;
    private org.jdesktop.swingx.JXLabel Date_Lbl;
    private org.jdesktop.swingx.JXPanel GRNPanel;
    private javax.swing.JScrollPane GRNTableScroll;
    private org.jdesktop.swingx.JXDatePicker GRN_Date;
    private org.jdesktop.swingx.JXLabel GRN_ID_Lbl;
    private org.jdesktop.swingx.JXLabel GRNdtailPanel;
    private org.jdesktop.swingx.JXTextField GRNnoTxt;
    private org.jdesktop.swingx.JXTable GRNtable;
    private org.jdesktop.swingx.JXLabel addBtn;
    private org.jdesktop.swingx.JXLabel addGRNbt;
    private org.jdesktop.swingx.JXComboBox batchNoComboBox;
    private org.jdesktop.swingx.JXLabel batchNoLbl;
    private org.jdesktop.swingx.JXLabel brandLbl;
    private org.jdesktop.swingx.JXTextField brandTxt;
    private org.jdesktop.swingx.JXPanel buttonPanel;
    private org.jdesktop.swingx.JXLabel companyLbl;
    private org.jdesktop.swingx.JXLabel companyWarrentLbl;
    private org.jdesktop.swingx.JXLabel deliQtyLbl;
    private org.jdesktop.swingx.JXTextField deliverdQtyTxt;
    private org.jdesktop.swingx.JXLabel itemDetailboaderLbl;
    private org.jdesktop.swingx.JXLabel itemDetailboaderLbl1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel modelNameLbl;
    private org.jdesktop.swingx.JXTextField modelNameTxt;
    private org.jdesktop.swingx.JXLabel modelNoLbl;
    private org.jdesktop.swingx.JXTextField modelNoTxt;
    private org.jdesktop.swingx.JXLabel newBatchBtn;
    private org.jdesktop.swingx.JXLabel newBt;
    private org.jdesktop.swingx.JXLabel printBtn;
    private org.jdesktop.swingx.JXComboBox supplierIdCombo;
    private org.jdesktop.swingx.JXTextField supplierNameTxt;
    private org.jdesktop.swingx.JXLabel supplierNmaeLbl;
    private org.jdesktop.swingx.JXLabel supplirIdLbl;
    private org.jdesktop.swingx.JXLabel title_lbl;
    private org.jdesktop.swingx.JXLabel totalAmountLbl;
    private org.jdesktop.swingx.JXTextField totalAmountTxt;
    private org.jdesktop.swingx.JXTextField unitPriceTxt;
    private org.jdesktop.swingx.JXLabel unitPricelbl;
    private org.jdesktop.swingx.JXLabel viewAllBtn;
    private org.jdesktop.swingx.JXTextField warrentyTxt;
    private org.jdesktop.swingx.JXLabel yearLbl1;
    private org.jdesktop.swingx.JXTextField yearTxt;
    // End of variables declaration//GEN-END:variables
    private static double GRNTTotalAmount = 0;
    private int addBtClickCount = 0;
    private int addButton = 0;
    private int saveBtn = 0;

    /**
     * @return the newBatchNo
     */
    public String getNewBatchNo() {
        return newBatchNo;
    }

    /**
     * @param newBatchNo the newBatchNo to set
     */
    public void setNewBatchNo(String newBatchNo) {
        this.newBatchNo = newBatchNo;
    }

    private void LoadCurrentDate() {
        Date date = new Date();
        DateFormat df = DateFormat.getDateInstance(DateFormat.FULL, Locale.ROOT);
        GRN_Date.setDate(date);
    }

}
