/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import java.awt.Font;
import java.net.URL;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Janitha Dhananjaya
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        setSize(1030, 680);
        start();
        

    }

    private void start() {
        
        CustomerInfoPanel custInfo = new CustomerInfoPanel();
        viewCustomerPanel.removeAll();
        viewCustomerPanel.add(custInfo);
        viewCustomerPanel.repaint();
        viewCustomerPanel.revalidate();
        viewCustomerPanel.setVisible(true);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        viewCustomerPanel = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewCustomerPanel.setBackground(new java.awt.Color(0, 0, 0));
        viewCustomerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXPanel1.add(viewCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        jXLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Blur background.jpg"))); // NOI18N
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel viewCustomerPanel;
    // End of variables declaration//GEN-END:variables
}
