/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import com.project.mobileshop.controller.CustomerController;
import com.project.mobileshop.controller.SupplierController;
import com.project.mobileshop.core.dto.CustomerDTO;
import com.project.mobileshop.core.dto.SupplierDTO;
import com.project.mobileshop.util.Validation;
import com.project.mobileshop.view.EditCustomerDialog;
import com.project.mobileshop.view.JoptionMessageDialog;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class CustomerInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerInfoPanel
     */
    public CustomerInfoPanel() {
        initComponents();
        LoadAllCustomers();
    }

    public void LoadAllCustomers() {

        try {
            ArrayList<CustomerDTO> AllIds = CustomerController.LoadAll();
            if (AllIds != null) {

                DefaultTableModel dtm = (DefaultTableModel) customerDetailsTable.getModel();
                dtm.setRowCount(0);

                for (CustomerDTO c : AllIds) {
                    Object[] row = {c.getCustomerId(), c.getCustomerName(), c.getContactNo(), c.getNICno()};
                    dtm.addRow(row);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CustomerInfoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        editCustomerBt = new org.jdesktop.swingx.JXLabel();
        customerPanel = new org.jdesktop.swingx.JXPanel();
        customerNamelbl = new org.jdesktop.swingx.JXLabel();
        customerIDlbl = new org.jdesktop.swingx.JXLabel();
        customerTable = new javax.swing.JScrollPane();
        customerDetailsTable = new org.jdesktop.swingx.JXTable();
        customerNameSearchField = new org.jdesktop.swingx.JXSearchField();
        customerIdSearchField = new org.jdesktop.swingx.JXSearchField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editCustomerBt.setBackground(new java.awt.Color(255, 255, 255));
        editCustomerBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editCustomerBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editCustomerBt.setText("Edit Customer");
        editCustomerBt.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        editCustomerBt.setOpaque(true);
        editCustomerBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editCustomerBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editCustomerBtMouseExited(evt);
            }
        });
        jXPanel1.add(editCustomerBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, 150, 50));

        customerPanel.setBackground(new java.awt.Color(255, 255, 255));
        customerPanel.setOpaque(false);
        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerNamelbl.setText("Customer Name");
        customerNamelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerPanel.add(customerNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 150, 40));

        customerIDlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerIDlbl.setText("Customer ID");
        customerIDlbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerPanel.add(customerIDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, 40));

        customerDetailsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customerDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Contact No", "NIC No"
            }
        ));
        customerDetailsTable.setEditable(false);
        customerDetailsTable.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        customerDetailsTable.setGridColor(new java.awt.Color(16, 151, 151));
        customerDetailsTable.setSelectionBackground(new java.awt.Color(0, 153, 102));
        customerTable.setViewportView(customerDetailsTable);

        customerPanel.add(customerTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 1000, 250));

        customerNameSearchField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerNameSearchField.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerNameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameSearchFieldActionPerformed(evt);
            }
        });
        customerPanel.add(customerNameSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 220, 40));

        customerIdSearchField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerIdSearchField.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerIdSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdSearchFieldActionPerformed(evt);
            }
        });
        customerPanel.add(customerIdSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 210, 40));

        jXLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel1.setOpaque(true);
        customerPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1000, 130));

        jXLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel2.setText("View Customer");
        jXLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        customerPanel.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 310, 70));

        jXPanel1.add(customerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editCustomerBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtMouseExited
        editCustomerBt.setBackground(new Color(255, 255, 255));
        editCustomerBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_editCustomerBtMouseExited

    private void editCustomerBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtMouseEntered
        editCustomerBt.setBackground(new Color(23,114,81));
        editCustomerBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_editCustomerBtMouseEntered

    private void editCustomerBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtMouseClicked
        if (customerDetailsTable.getSelectedRow() == -1) {
            
            String content = "Select a customer to edit";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }
        int customerRow = customerDetailsTable.getSelectedRow();

        String customerID = customerDetailsTable.getValueAt(customerRow, 0).toString();
        String customerName = customerDetailsTable.getValueAt(customerRow, 1).toString();
        int contactNo = Integer.parseInt(customerDetailsTable.getValueAt(customerRow, 2).toString());
        String NICno = customerDetailsTable.getValueAt(customerRow, 3).toString();

        CustomerDTO customerDTO = new CustomerDTO(customerID, customerName, contactNo, NICno);
        EditCustomerDialog customerDialog = new EditCustomerDialog(null, true);
        customerDialog.getInfo(customerDTO);

        customerDialog.setVisible(true);
    }//GEN-LAST:event_editCustomerBtMouseClicked

    private void customerIdSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdSearchFieldActionPerformed

        if (customerIdSearchField.getText().equals("")) {
            LoadAllCustomers();
            return;
        }

        String customerId = customerIdSearchField.getText();
        CustomerDTO customerDTO = new CustomerDTO();
        customerDTO.setCustomerId(customerId);
        try {
            CustomerDTO search = CustomerController.searchFromID(customerDTO);
            if (search != null) {
                DefaultTableModel dtm = (DefaultTableModel) customerDetailsTable.getModel();
                dtm.setRowCount(0);
                Object[] row = {search.getCustomerId(), search.getCustomerName(), search.getContactNo(), search.getNICno()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerInfoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerIdSearchFieldActionPerformed

    private void customerNameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameSearchFieldActionPerformed
        if (customerIdSearchField.getText().equals("")) {
            LoadAllCustomers();
           
        }

        String customerName = customerNameSearchField.getText();
        CustomerDTO customerDTO = new CustomerDTO();
        customerDTO.setCustomerName(customerName);
        try {
            CustomerDTO search = CustomerController.searchFromName(customerDTO);
            if (search != null) {
                DefaultTableModel dtm = (DefaultTableModel) customerDetailsTable.getModel();
                dtm.setRowCount(0);
                Object[] row = {search.getCustomerId(), search.getCustomerName(), search.getContactNo(), search.getNICno()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerInfoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerNameSearchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTable customerDetailsTable;
    private org.jdesktop.swingx.JXLabel customerIDlbl;
    private org.jdesktop.swingx.JXSearchField customerIdSearchField;
    private org.jdesktop.swingx.JXSearchField customerNameSearchField;
    private org.jdesktop.swingx.JXLabel customerNamelbl;
    private org.jdesktop.swingx.JXPanel customerPanel;
    private javax.swing.JScrollPane customerTable;
    private org.jdesktop.swingx.JXLabel editCustomerBt;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables
}
