/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Janitha Dhananjaya
 */
public class MobilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    public MobilePanel() {
        initComponents();
        QuickSearch();
        start();
    }

    private void QuickSearch() {
        QuickSearchPanel search = new QuickSearchPanel();
        productPanel.removeAll();
        productPanel.add(search);
        productPanel.repaint();
        productPanel.revalidate();
        productPanel.setVisible(true);
    }

    public void start() {
        quickSearchBtn.setFont(new Font("", 1, 18));
        quickSearchBtn.setBackground(new Color(23, 114, 81));
        quickSearchBtn.setForeground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductMainPanel = new org.jdesktop.swingx.JXPanel();
        buttonPanel = new org.jdesktop.swingx.JXPanel();
        returnMobileBtn = new org.jdesktop.swingx.JXLabel();
        specificationBtn = new org.jdesktop.swingx.JXLabel();
        quickSearchBtn = new org.jdesktop.swingx.JXLabel();
        manageMobileBtn = new org.jdesktop.swingx.JXLabel();
        productPanel = new org.jdesktop.swingx.JXPanel();
        imageBackLbl = new org.jdesktop.swingx.JXLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonPanel.setOpaque(false);
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnMobileBtn.setBackground(new java.awt.Color(255, 255, 204));
        returnMobileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        returnMobileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnMobileBtn.setText("Return Mobile");
        returnMobileBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        returnMobileBtn.setOpaque(true);
        returnMobileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnMobileBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnMobileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnMobileBtnMouseExited(evt);
            }
        });
        buttonPanel.add(returnMobileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 210, 50));

        specificationBtn.setBackground(new java.awt.Color(255, 255, 204));
        specificationBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        specificationBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        specificationBtn.setText("Specifications");
        specificationBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        specificationBtn.setOpaque(true);
        specificationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specificationBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                specificationBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                specificationBtnMouseExited(evt);
            }
        });
        buttonPanel.add(specificationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 230, 50));

        quickSearchBtn.setBackground(new java.awt.Color(255, 255, 204));
        quickSearchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quickSearchBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quickSearchBtn.setText("Quick Search");
        quickSearchBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        quickSearchBtn.setOpaque(true);
        quickSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quickSearchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quickSearchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quickSearchBtnMouseExited(evt);
            }
        });
        buttonPanel.add(quickSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 220, 50));

        manageMobileBtn.setBackground(new java.awt.Color(255, 255, 204));
        manageMobileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        manageMobileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageMobileBtn.setText("Manage Mobile");
        manageMobileBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        manageMobileBtn.setOpaque(true);
        manageMobileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMobileBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageMobileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageMobileBtnMouseExited(evt);
            }
        });
        buttonPanel.add(manageMobileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 220, 50));

        ProductMainPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        productPanel.setBackground(new java.awt.Color(0, 0, 0));
        productPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ProductMainPanel.add(productPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1060, 630));

        imageBackLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Blur background.jpg"))); // NOI18N
        ProductMainPanel.add(imageBackLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        add(ProductMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void quickSearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSearchBtnMouseClicked
        quickSearchBtn.setBackground(new Color(23, 114, 81));
        quickSearchBtn.setForeground(new Color(255, 255, 255));

        specificationBtn.setBackground(new Color(255, 255, 204));
        specificationBtn.setForeground(new Color(0, 0, 0));

        returnMobileBtn.setBackground(new Color(255, 255, 204));
        returnMobileBtn.setForeground(new Color(0, 0, 0));
        
        manageMobileBtn.setBackground(new Color(255, 255, 204));
        manageMobileBtn.setForeground(new Color(0, 0, 0));

        QuickSearchPanel search = new QuickSearchPanel();
        productPanel.removeAll();
        productPanel.add(search);
        productPanel.repaint();
        productPanel.revalidate();
        productPanel.setVisible(true);
    }//GEN-LAST:event_quickSearchBtnMouseClicked

    private void specificationBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specificationBtnMouseClicked
        specificationBtn.setBackground(new Color(23, 114, 81));
        specificationBtn.setForeground(new Color(255, 255, 255));

        quickSearchBtn.setBackground(new Color(255, 255, 204));
        quickSearchBtn.setForeground(new Color(0, 0, 0));

        returnMobileBtn.setBackground(new Color(255, 255, 204));
        returnMobileBtn.setForeground(new Color(0, 0, 0));

        manageMobileBtn.setBackground(new Color(255, 255, 204));
        manageMobileBtn.setForeground(new Color(0, 0, 0));
        
        Specifications updateItem = new Specifications();
        productPanel.removeAll();
        productPanel.add(updateItem);
        productPanel.repaint();
        productPanel.revalidate();
        productPanel.setVisible(true);
    }//GEN-LAST:event_specificationBtnMouseClicked

    private void returnMobileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnMobileBtnMouseClicked
        returnMobileBtn.setBackground(new Color(23, 114, 81));
        returnMobileBtn.setForeground(new Color(255, 255, 255));

        quickSearchBtn.setBackground(new Color(255, 255, 204));
        quickSearchBtn.setForeground(new Color(0, 0, 0));

        specificationBtn.setBackground(new Color(255, 255, 204));
        specificationBtn.setForeground(new Color(0, 0, 0));

        manageMobileBtn.setBackground(new Color(255, 255, 204));
        manageMobileBtn.setForeground(new Color(0, 0, 0));
        
        ReturnMobilePanel deletePanel = new ReturnMobilePanel();
        productPanel.removeAll();
        productPanel.add(deletePanel);
        productPanel.repaint();
        productPanel.revalidate();
        productPanel.setVisible(true);
    }//GEN-LAST:event_returnMobileBtnMouseClicked

    private void quickSearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSearchBtnMouseEntered
        quickSearchBtn.setFont(new Font("", 1, 24));
    }//GEN-LAST:event_quickSearchBtnMouseEntered

    private void quickSearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSearchBtnMouseExited
        quickSearchBtn.setFont(new Font("", 1, 18));
    }//GEN-LAST:event_quickSearchBtnMouseExited

    private void specificationBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specificationBtnMouseEntered
        specificationBtn.setFont(new Font("", 1, 24));
    }//GEN-LAST:event_specificationBtnMouseEntered

    private void specificationBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specificationBtnMouseExited
        specificationBtn.setFont(new Font("", 1, 18));
    }//GEN-LAST:event_specificationBtnMouseExited

    private void returnMobileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnMobileBtnMouseEntered
        returnMobileBtn.setFont(new Font("", 1, 21));
    }//GEN-LAST:event_returnMobileBtnMouseEntered

    private void returnMobileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnMobileBtnMouseExited
        returnMobileBtn.setFont(new Font("", 1, 18));
    }//GEN-LAST:event_returnMobileBtnMouseExited

    private void manageMobileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMobileBtnMouseClicked
        manageMobileBtn.setBackground(new Color(23, 114, 81));
        manageMobileBtn.setForeground(new Color(255, 255, 255));

        quickSearchBtn.setBackground(new Color(255, 255, 204));
        quickSearchBtn.setForeground(new Color(0, 0, 0));

        specificationBtn.setBackground(new Color(255, 255, 204));
        specificationBtn.setForeground(new Color(0, 0, 0));

        returnMobileBtn.setBackground(new Color(255, 255, 204));
        returnMobileBtn.setForeground(new Color(0, 0, 0));

        ManageMobilePanel manage = new ManageMobilePanel();
        productPanel.removeAll();
        productPanel.add(manage);
        productPanel.repaint();
        productPanel.revalidate();
        productPanel.setVisible(true);
    }//GEN-LAST:event_manageMobileBtnMouseClicked

    private void manageMobileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMobileBtnMouseEntered
        manageMobileBtn.setFont(new Font("", 1, 24));
    }//GEN-LAST:event_manageMobileBtnMouseEntered

    private void manageMobileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMobileBtnMouseExited
        manageMobileBtn.setFont(new Font("", 1, 18));
    }//GEN-LAST:event_manageMobileBtnMouseExited

    public static void main(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel ProductMainPanel;
    private org.jdesktop.swingx.JXPanel buttonPanel;
    private org.jdesktop.swingx.JXLabel imageBackLbl;
    private org.jdesktop.swingx.JXLabel manageMobileBtn;
    private org.jdesktop.swingx.JXPanel productPanel;
    private org.jdesktop.swingx.JXLabel quickSearchBtn;
    private org.jdesktop.swingx.JXLabel returnMobileBtn;
    private org.jdesktop.swingx.JXLabel specificationBtn;
    // End of variables declaration//GEN-END:variables
}
