/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import com.project.mobileshop.controller.CustomerController;
import com.project.mobileshop.controller.InvoiceController;
import com.project.mobileshop.controller.MobileController;
import com.project.mobileshop.controller.MobileDetailController;
import com.project.mobileshop.controller.ModelController;
import com.project.mobileshop.core.dto.CustomDTO;
import com.project.mobileshop.core.dto.CustomerDTO;
import com.project.mobileshop.core.dto.InvoiceDTO;
import com.project.mobileshop.core.dto.MobileDTO;
import com.project.mobileshop.core.dto.MobileDetailDTO;
import com.project.mobileshop.core.dto.ModelDTO;
import com.project.mobileshop.db.DBConnection;
import com.project.mobileshop.idgeneretor.IDGenerator;
import com.project.mobileshop.view.JoptionMessageDialog;
import com.project.mobileshop.view.addNewCustomer;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Font;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.DatePicker;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author Janitha Dhananjaya
 */
@Report("com.project.mobileshop.report")
public class OrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
        LoadCustomerIds();
        LoadBrands();
        LoadCurrentDate();
        generateInvoiceID();
        DisabledDates();
    }

    public void LoadCurrentDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String curDate = dateFormat.format(date);
        orderDate.setDate(date);
    }

    public void generateInvoiceID() {
        try {
            invoiceIdTxt.setText(IDGenerator.getNewID("invoice", "invoiceId", "I"));
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void LoadCustomerIds() {
        try {
            ArrayList<CustomerDTO> customerIds = CustomerController.LoadAll();
            for (CustomerDTO c : customerIds) {
                customerComboBox.addItem(c.getCustomerId());
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadBrands() {
        try {
            ArrayList<ModelDTO> LoadModelNos = ModelController.getBrands();
            for (ModelDTO M : LoadModelNos) {
                brandCmb.addItem(M.getBrand());
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placeOrderPanel = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        custI_lbl1 = new javax.swing.JLabel();
        cust_name_lbl1 = new javax.swing.JLabel();
        cust_name_txt = new javax.swing.JTextField();
        cont_no_lbl1 = new javax.swing.JLabel();
        cont_no_txt1 = new javax.swing.JTextField();
        cust_info_lbl = new javax.swing.JLabel();
        pro_info_lbl = new javax.swing.JLabel();
        iten_name_lbl = new javax.swing.JLabel();
        qty_on_hand_lbl = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        cust_info_lbl1 = new javax.swing.JLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        amountTxt = new org.jdesktop.swingx.JXTextField();
        amount_paidTxt = new org.jdesktop.swingx.JXTextField();
        balanceTxt = new org.jdesktop.swingx.JXTextField();
        cancelBt = new org.jdesktop.swingx.JXLabel();
        item_code_lbl = new javax.swing.JLabel();
        original_price_lbl3 = new javax.swing.JLabel();
        IMEInoTxt = new javax.swing.JTextField();
        originalPricetxt = new javax.swing.JTextField();
        discountTxt = new javax.swing.JTextField();
        original_price_lbl2 = new javax.swing.JLabel();
        original_price_lbl1 = new javax.swing.JLabel();
        selling_price_txt = new javax.swing.JTextField();
        orderBt = new org.jdesktop.swingx.JXLabel();
        custI_lbl2 = new javax.swing.JLabel();
        orderDate = new org.jdesktop.swingx.JXDatePicker();
        dateLbl = new org.jdesktop.swingx.JXLabel();
        invoiceIdTxt = new org.jdesktop.swingx.JXTextField();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        customerComboBox = new org.jdesktop.swingx.JXComboBox();
        item_code_lbl1 = new javax.swing.JLabel();
        newCustomerBtn = new org.jdesktop.swingx.JXLabel();
        itemNamecmb = new org.jdesktop.swingx.JXComboBox();
        modelNoTxt = new javax.swing.JTextField();
        qty_on_hand_lbl1 = new javax.swing.JLabel();
        brandCmb = new org.jdesktop.swingx.JXComboBox();
        qty_on_hand_lbl2 = new javax.swing.JLabel();
        compayWarrentyPeriodTxt = new javax.swing.JTextField();
        warrentyPeriodLbl1 = new javax.swing.JLabel();
        qtyy_on_hand_txt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placeOrderPanel.setBackground(new java.awt.Color(255, 255, 255));
        placeOrderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("Place Order");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        placeOrderPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 270, 40));

        custI_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        custI_lbl1.setText("Customer ID");
        placeOrderPanel.add(custI_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        cust_name_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        cust_name_lbl1.setText("Customer Name");
        placeOrderPanel.add(cust_name_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        cust_name_txt.setEditable(false);
        cust_name_txt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        cust_name_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cust_name_txt.setOpaque(false);
        cust_name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cust_name_txtKeyPressed(evt);
            }
        });
        placeOrderPanel.add(cust_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 30));

        cont_no_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        cont_no_lbl1.setText("Contact No");
        placeOrderPanel.add(cont_no_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        cont_no_txt1.setEditable(false);
        cont_no_txt1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        cont_no_txt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cont_no_txt1.setOpaque(false);
        placeOrderPanel.add(cont_no_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, 30));

        cust_info_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cust_info_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cust_info_lbl.setText("Customer Info :-");
        cust_info_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        placeOrderPanel.add(cust_info_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 124, 30));

        pro_info_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        pro_info_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pro_info_lbl.setText("Product Info :-");
        pro_info_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        placeOrderPanel.add(pro_info_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 30));

        iten_name_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        iten_name_lbl.setText("Model Name");
        placeOrderPanel.add(iten_name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 440, 130, 30));

        qty_on_hand_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        qty_on_hand_lbl.setText("Year");
        placeOrderPanel.add(qty_on_hand_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 70, 30));

        yearTxt.setEditable(false);
        yearTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        yearTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        yearTxt.setOpaque(false);
        placeOrderPanel.add(yearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 200, 30));

        jXPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cust_info_lbl1.setBackground(new java.awt.Color(0, 204, 204));
        cust_info_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cust_info_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cust_info_lbl1.setText("Order Info :-");
        cust_info_lbl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jXPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jXLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel5.setText("Amount");
        jXLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        jXLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel6.setText("Amount Paid");
        jXLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        jXLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel7.setText("Balance");
        jXLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        amountTxt.setEditable(false);
        amountTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        amountTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtActionPerformed(evt);
            }
        });

        amount_paidTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        amount_paidTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amount_paidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_paidTxtActionPerformed(evt);
            }
        });
        amount_paidTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amount_paidTxtKeyTyped(evt);
            }
        });

        balanceTxt.setEditable(false);
        balanceTxt.setForeground(new java.awt.Color(255, 0, 0));
        balanceTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        balanceTxt.setEnabled(false);
        balanceTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(amountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(amount_paidTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_paidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cancelBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelBt.setText("Cancel");
        cancelBt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        cancelBt.setOpaque(true);
        cancelBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtMouseExited(evt);
            }
        });

        item_code_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        item_code_lbl.setText("IMEI No");

        original_price_lbl3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        original_price_lbl3.setText("Original Price");

        IMEInoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        IMEInoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        IMEInoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IMEInoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMEInoTxtActionPerformed(evt);
            }
        });
        IMEInoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IMEInoTxtKeyTyped(evt);
            }
        });

        originalPricetxt.setEditable(false);
        originalPricetxt.setBackground(new java.awt.Color(255, 255, 255));
        originalPricetxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        originalPricetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        discountTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        discountTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        discountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTxtActionPerformed(evt);
            }
        });

        original_price_lbl2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        original_price_lbl2.setText("Discount");

        original_price_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        original_price_lbl1.setText("Unit Price");

        selling_price_txt.setEditable(false);
        selling_price_txt.setBackground(new java.awt.Color(255, 255, 255));
        selling_price_txt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        selling_price_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        orderBt.setBackground(new java.awt.Color(255, 255, 255));
        orderBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        orderBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderBt.setText("ORDER");
        orderBt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        orderBt.setOpaque(true);
        orderBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderBtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jXPanel4Layout = new javax.swing.GroupLayout(jXPanel4);
        jXPanel4.setLayout(jXPanel4Layout);
        jXPanel4Layout.setHorizontalGroup(
            jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cust_info_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(item_code_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(IMEInoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(original_price_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(originalPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(original_price_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(selling_price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(original_price_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(discountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(orderBt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jXPanel4Layout.setVerticalGroup(
            jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addComponent(cancelBt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jXPanel4Layout.createSequentialGroup()
                        .addComponent(cust_info_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item_code_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IMEInoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(original_price_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originalPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(original_price_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selling_price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(original_price_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(orderBt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        placeOrderPanel.add(jXPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 560, 520));

        custI_lbl2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        custI_lbl2.setText("Invoice ID");
        placeOrderPanel.add(custI_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 120, 30));
        placeOrderPanel.add(orderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, 30));

        dateLbl.setText("Date");
        dateLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        placeOrderPanel.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 30));

        invoiceIdTxt.setEditable(false);
        invoiceIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        invoiceIdTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        invoiceIdTxt.setOpaque(false);
        invoiceIdTxt.setPromptForeground(new java.awt.Color(0, 0, 0));
        placeOrderPanel.add(invoiceIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 110, 30));

        jXLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        placeOrderPanel.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1000, 50));

        customerComboBox.setBackground(new java.awt.Color(231, 254, 254));
        customerComboBox.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerComboBoxItemStateChanged(evt);
            }
        });
        customerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboBoxActionPerformed(evt);
            }
        });
        placeOrderPanel.add(customerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 190, 30));

        item_code_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        item_code_lbl1.setText("Model No");
        placeOrderPanel.add(item_code_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 480, 130, 30));

        newCustomerBtn.setBackground(new java.awt.Color(51, 153, 0));
        newCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        newCustomerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newCustomerBtn.setText("New");
        newCustomerBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        newCustomerBtn.setOpaque(true);
        newCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newCustomerBtnMouseClicked(evt);
            }
        });
        placeOrderPanel.add(newCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 60, 30));

        itemNamecmb.setBackground(new java.awt.Color(231, 254, 254));
        itemNamecmb.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        itemNamecmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemNamecmbItemStateChanged(evt);
            }
        });
        itemNamecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNamecmbActionPerformed(evt);
            }
        });
        placeOrderPanel.add(itemNamecmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 200, 30));

        modelNoTxt.setEditable(false);
        modelNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNoTxt.setOpaque(false);
        placeOrderPanel.add(modelNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 200, 30));

        qty_on_hand_lbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        qty_on_hand_lbl1.setText("Brand");
        placeOrderPanel.add(qty_on_hand_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 400, 100, 30));

        brandCmb.setBackground(new java.awt.Color(231, 254, 254));
        brandCmb.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        brandCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brandCmbItemStateChanged(evt);
            }
        });
        brandCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandCmbActionPerformed(evt);
            }
        });
        placeOrderPanel.add(brandCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 200, 30));

        qty_on_hand_lbl2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        qty_on_hand_lbl2.setText("Qty On Hand");
        placeOrderPanel.add(qty_on_hand_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 130, 30));

        compayWarrentyPeriodTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        compayWarrentyPeriodTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        compayWarrentyPeriodTxt.setOpaque(false);
        placeOrderPanel.add(compayWarrentyPeriodTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 200, 30));

        warrentyPeriodLbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        warrentyPeriodLbl1.setText("Warrenty");
        placeOrderPanel.add(warrentyPeriodLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 110, 30));

        qtyy_on_hand_txt.setEditable(false);
        qtyy_on_hand_txt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        qtyy_on_hand_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        qtyy_on_hand_txt.setOpaque(false);
        placeOrderPanel.add(qtyy_on_hand_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 200, 30));

        add(placeOrderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void amountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtActionPerformed
        amount_paidTxt.requestFocus();
    }//GEN-LAST:event_amountTxtActionPerformed

    private void amount_paidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_paidTxtActionPerformed
        double Amount = Double.parseDouble(amountTxt.getText());
        double paidAmount = Double.parseDouble(amount_paidTxt.getText());
        double balance = paidAmount - Amount;
        balanceTxt.setText(String.valueOf(balance));

        if (paidAmount < Amount) {
            String content = "Paid amount not enough";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        balanceTxt.requestFocus();

    }//GEN-LAST:event_amount_paidTxtActionPerformed

    private void balanceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceTxtActionPerformed

    private void orderBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtMouseEntered
        orderBt.setBackground(new Color(23, 114, 81));
        orderBt.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_orderBtMouseEntered

    private void orderBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtMouseExited
        orderBt.setBackground(new Color(255, 255, 255));
        orderBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_orderBtMouseExited

    private void cancelBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtMouseEntered
        cancelBt.setBackground(new Color(255, 14, 65));
        cancelBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_cancelBtMouseEntered

    private void cancelBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtMouseExited
        cancelBt.setBackground(new Color(255, 255, 255));
        cancelBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_cancelBtMouseExited

    private void customerComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerComboBoxItemStateChanged

    }//GEN-LAST:event_customerComboBoxItemStateChanged

    private void itemNamecmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemNamecmbItemStateChanged
        if (itemNamecmb.getSelectedIndex() == -1) {
            return;
        }
        String modelName = itemNamecmb.getSelectedItem().toString();
        try {
            ModelDTO OrderModelDetails = ModelController.OrderModelDetails(modelName);
            if (OrderModelDetails != null) {
                modelNoTxt.setText(OrderModelDetails.getModelNo());
                yearTxt.setText(String.valueOf(OrderModelDetails.getYear()));
                qtyy_on_hand_txt.setText(String.valueOf(OrderModelDetails.getQtyOnHand()));
                compayWarrentyPeriodTxt.setText(String.valueOf(OrderModelDetails.getWarrentyPeriod()));

            }
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_itemNamecmbItemStateChanged

    private void customerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboBoxActionPerformed
        String customerId = customerComboBox.getSelectedItem().toString();
        CustomerDTO customerDTO = new CustomerDTO();
        customerDTO.setCustomerId(customerId);
        try {
            CustomerDTO info = CustomerController.searchFromID(customerDTO);

            cust_name_txt.setText(info.getCustomerName());
            cont_no_txt1.setText(String.valueOf(info.getContactNo()));

        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerComboBoxActionPerformed

    private void itemNamecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNamecmbActionPerformed


    }//GEN-LAST:event_itemNamecmbActionPerformed

    private void IMEInoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMEInoTxtActionPerformed
        String IMEIno = IMEInoTxt.getText();
        String modelNo = modelNoTxt.getText();
        MobileDetailDTO dTO = new MobileDetailDTO();
        dTO.setIMEIno(IMEIno);
        dTO.setModelNo(modelNo);
        try {
            int searchModelNo = MobileDetailController.searchModelNo(dTO);
            if (searchModelNo == 2) {
                originalPricetxt.setText("");
                selling_price_txt.setText("");
                discountTxt.setText("");

                String content = "Recheck Model Name!";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);

                return;
            } else if (searchModelNo == 0) {
                String content = "No Mobile found for this IEMI no";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            CustomDTO mobileDetails = MobileDetailController.MobileDetails(IMEIno);

            if (mobileDetails != null) {
                status = mobileDetails.getStatus();
                batchNo = mobileDetails.getBathcNo();

                if (status.equals("Sold")) {

                    String content = "This mobie is already sold";
                    JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                    dialog.getContent(content);
                    return;

                }

                originalPricetxt.setText(String.valueOf(mobileDetails.getUnitPrice()));
                selling_price_txt.setText(String.valueOf(mobileDetails.getSellingPrice()));
                discountTxt.setText("0.00");
                discountTxt.requestFocus();

            }
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_IMEInoTxtActionPerformed

    private void brandCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brandCmbItemStateChanged
        itemNamecmb.removeAllItems();

        String brand = brandCmb.getSelectedItem().toString();
        try {
            ArrayList<CustomDTO> modelNames = ModelController.getModelNames(brand);
            if (modelNames != null) {
                for (CustomDTO m : modelNames) {
                    itemNamecmb.addItem(m.getModelName());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brandCmbItemStateChanged

    private void brandCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandCmbActionPerformed

    private void newCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCustomerBtnMouseClicked
        addNewCustomer addCustomer = new addNewCustomer(null, true);
        addCustomer.setVisible(true);
    }//GEN-LAST:event_newCustomerBtnMouseClicked

    private void discountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTxtActionPerformed
        if (IMEInoTxt.getText().trim().isEmpty()) {

            String content = "Enter the IEMI Number";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        double sellingPrice = Double.parseDouble(selling_price_txt.getText());
        double discount = Double.parseDouble(discountTxt.getText());
        double balance = (sellingPrice) - (discount);

        amountTxt.setText(String.valueOf(balance));
        amount_paidTxt.requestFocus();
    }//GEN-LAST:event_discountTxtActionPerformed

    private void orderBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtMouseClicked
        String IMEIno = IMEInoTxt.getText();

        Date order = orderDate.getDate();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String orderDate = date.format(order);

        if (IMEIno.trim().isEmpty()) {

            String content = "Fill all order details";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        String invoiceId = invoiceIdTxt.getText();
        BigDecimal totalAmout = new BigDecimal(amountTxt.getText());

        String modelNo = modelNoTxt.getText();

        String originalPrice = originalPricetxt.getText();
        String unitPrice = selling_price_txt.getText();
        String discont = discountTxt.getText();
        String paidAmount = amount_paidTxt.getText();

        String updateStatus = "Sold";

        String mobileNo = invoiceId.substring(3, 4);

        MobileDTO mobileDTO = new MobileDTO(mobileNo, IMEIno, customerComboBox.getSelectedItem().toString(), modelNo, invoiceId, Integer.parseInt(compayWarrentyPeriodTxt.getText()));

        InvoiceDTO invoiceDTO = new InvoiceDTO(invoiceId, orderDate, totalAmout);

        try {
            boolean isPlaced = InvoiceController.placeOrder(invoiceDTO, mobileDTO, updateStatus, batchNo, IMEIno, modelNo);
            if (isPlaced) {

                String content = "Order Successfully placed";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);

                JasperUtil.init(OrderPanel.class);

                JasperReportsContext ctx = JasperUtil.getReportContext();

                try {
                    JasperReport compiledReport = JasperUtil.getCompiledReport("Invoice.jasper");

                    JasperFillManager fillManager = JasperFillManager.getInstance(ctx);

                    HashMap<String, Object> reportParams = new HashMap<>();

                    reportParams.put("invoiceid", invoiceIdTxt.getText());

                    Connection connection = DBConnection.getInstance().getConnection();
                    JasperPrint filledReport = fillManager.fill(compiledReport, reportParams, connection);

                    IJSEJasperViewer frmJSEJasperViewer = new IJSEJasperViewer(filledReport);
                    frmJSEJasperViewer.setTitle("Customer Details Report");
                    frmJSEJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
                    frmJSEJasperViewer.setVisible(true);

                } catch (JRException ex) {
                    Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {

                String content = "Order not placed";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }
        } catch (Exception ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_orderBtMouseClicked

    private void amount_paidTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amount_paidTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = IMEInoTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_amount_paidTxtKeyTyped

    private void IMEInoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMEInoTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = IMEInoTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_IMEInoTxtKeyTyped

    private void cust_name_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cust_name_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_name_txtKeyPressed

    private void cancelBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtMouseClicked
        IMEInoTxt.setText("");
        originalPricetxt.setText("");
        selling_price_txt.setText("");
        discountTxt.setText("");
        amountTxt.setText("");
        amount_paidTxt.setText("");
        balanceTxt.setText("");

    }//GEN-LAST:event_cancelBtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IMEInoTxt;
    private org.jdesktop.swingx.JXTextField amountTxt;
    private org.jdesktop.swingx.JXTextField amount_paidTxt;
    private org.jdesktop.swingx.JXTextField balanceTxt;
    private org.jdesktop.swingx.JXComboBox brandCmb;
    private org.jdesktop.swingx.JXLabel cancelBt;
    private javax.swing.JTextField compayWarrentyPeriodTxt;
    private javax.swing.JLabel cont_no_lbl1;
    private javax.swing.JTextField cont_no_txt1;
    private javax.swing.JLabel custI_lbl1;
    private javax.swing.JLabel custI_lbl2;
    private javax.swing.JLabel cust_info_lbl;
    private javax.swing.JLabel cust_info_lbl1;
    private javax.swing.JLabel cust_name_lbl1;
    private javax.swing.JTextField cust_name_txt;
    private org.jdesktop.swingx.JXComboBox customerComboBox;
    private org.jdesktop.swingx.JXLabel dateLbl;
    private javax.swing.JTextField discountTxt;
    private org.jdesktop.swingx.JXTextField invoiceIdTxt;
    private org.jdesktop.swingx.JXComboBox itemNamecmb;
    private javax.swing.JLabel item_code_lbl;
    private javax.swing.JLabel item_code_lbl1;
    private javax.swing.JLabel iten_name_lbl;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private javax.swing.JTextField modelNoTxt;
    private org.jdesktop.swingx.JXLabel newCustomerBtn;
    private org.jdesktop.swingx.JXLabel orderBt;
    private org.jdesktop.swingx.JXDatePicker orderDate;
    private javax.swing.JTextField originalPricetxt;
    private javax.swing.JLabel original_price_lbl1;
    private javax.swing.JLabel original_price_lbl2;
    private javax.swing.JLabel original_price_lbl3;
    private org.jdesktop.swingx.JXPanel placeOrderPanel;
    private javax.swing.JLabel pro_info_lbl;
    private javax.swing.JLabel qty_on_hand_lbl;
    private javax.swing.JLabel qty_on_hand_lbl1;
    private javax.swing.JLabel qty_on_hand_lbl2;
    private javax.swing.JTextField qtyy_on_hand_txt;
    private javax.swing.JTextField selling_price_txt;
    private javax.swing.JLabel warrentyPeriodLbl1;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
    private String status = null;
    private String batchNo = null;

    private void DisabledDates() {
        Date date = new Date();
        orderDate.getMonthView().setUpperBound(date);
    }
}
