/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import com.project.mobileshop.controller.ReturnMobileController;
import com.project.mobileshop.core.dto.CustomDTO;
import com.project.mobileshop.core.dto.ReturnMobileDTO;
import com.project.mobileshop.idgeneretor.IDGenerator;
import com.project.mobileshop.util.Validation;
import com.project.mobileshop.view.ChangeAccountSettingsDialog;
import com.project.mobileshop.view.JoptionMessageDialog;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Janitha Dhananjaya
 */
public class ReturnMobilePanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteItemPanel
     */
    public ReturnMobilePanel() {
        initComponents();
        generateRepirID();
        statusLbl.setVisible(false);
        LoadCurrentDate();

    }

    public void generateRepirID() {
        try {
            returnIDTxt.setText(IDGenerator.getNewID("returnmobile", "retrunId", "R"));
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        InnerPanel = new org.jdesktop.swingx.JXPanel();
        IMEINILbl = new javax.swing.JLabel();
        IMEINoTxt = new javax.swing.JTextField();
        issueLbl = new javax.swing.JLabel();
        issueTxt = new javax.swing.JTextField();
        soldInvNoLbl = new javax.swing.JLabel();
        warrantyLbl = new javax.swing.JLabel();
        warrentyTxt = new javax.swing.JTextField();
        clearBtn = new org.jdesktop.swingx.JXLabel();
        Title_lbl = new org.jdesktop.swingx.JXLabel();
        saveBtn = new org.jdesktop.swingx.JXLabel();
        customerNameLbl = new javax.swing.JLabel();
        customerNameTxt = new javax.swing.JTextField();
        custmerIDLbl = new javax.swing.JLabel();
        supplierNameTxt = new javax.swing.JTextField();
        supplierNameLbl = new javax.swing.JLabel();
        supplierIDLbl = new javax.swing.JLabel();
        supplierIDTxt = new javax.swing.JTextField();
        soldDateTxt = new javax.swing.JTextField();
        customerIDTxt = new javax.swing.JTextField();
        soldInvNoTxt = new javax.swing.JTextField();
        soldDateLbl = new javax.swing.JLabel();
        statusLbl = new org.jdesktop.swingx.JXLabel();
        mobileDetailsLbl1 = new org.jdesktop.swingx.JXLabel();
        repeirDetailsPanel = new org.jdesktop.swingx.JXPanel();
        returnIDTxt = new javax.swing.JTextField();
        returnIDLbl = new javax.swing.JLabel();
        dateLBl = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        mobileDetailsLbl = new org.jdesktop.swingx.JXLabel();
        allRetrunMobileBtn = new org.jdesktop.swingx.JXLabel();

        setPreferredSize(new java.awt.Dimension(1060, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InnerPanel.setBackground(new java.awt.Color(255, 255, 255));
        InnerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IMEINILbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        IMEINILbl.setText("IMEI No");
        InnerPanel.add(IMEINILbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, 30));

        IMEINoTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        IMEINoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        IMEINoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IMEINoTxt.setOpaque(false);
        IMEINoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMEINoTxtActionPerformed(evt);
            }
        });
        IMEINoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IMEINoTxtKeyTyped(evt);
            }
        });
        InnerPanel.add(IMEINoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 260, 30));

        issueLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        issueLbl.setText("Issue");
        InnerPanel.add(issueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 70, 30));

        issueTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        issueTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        issueTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        issueTxt.setOpaque(false);
        InnerPanel.add(issueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 220, 30));

        soldInvNoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        soldInvNoLbl.setText("Sold Invoice No");
        InnerPanel.add(soldInvNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 160, 30));

        warrantyLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        warrantyLbl.setText("Warrenty Period");
        InnerPanel.add(warrantyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 160, 30));

        warrentyTxt.setEditable(false);
        warrentyTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        warrentyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        warrentyTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        warrentyTxt.setOpaque(false);
        warrentyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrentyTxtActionPerformed(evt);
            }
        });
        InnerPanel.add(warrentyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 220, 30));

        clearBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 14, 65)));
        clearBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clearBtn.setText("Clear");
        clearBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        clearBtn.setOpaque(true);
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        InnerPanel.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 90, 40));

        Title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_lbl.setText("Return Mobile");
        Title_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        InnerPanel.add(Title_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 270, 30));

        saveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81)));
        saveBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveBtn.setText("Save");
        saveBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        saveBtn.setOpaque(true);
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });
        InnerPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 90, 40));

        customerNameLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerNameLbl.setText("Customer Name");
        InnerPanel.add(customerNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, 30));

        customerNameTxt.setEditable(false);
        customerNameTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        customerNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerNameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        customerNameTxt.setOpaque(false);
        InnerPanel.add(customerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, 30));

        custmerIDLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        custmerIDLbl.setText("Customer Id");
        InnerPanel.add(custmerIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 120, 30));

        supplierNameTxt.setEditable(false);
        supplierNameTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        supplierNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supplierNameTxt.setOpaque(false);
        supplierNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtActionPerformed(evt);
            }
        });
        InnerPanel.add(supplierNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 220, 30));

        supplierNameLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supplierNameLbl.setText("Supplier Name");
        InnerPanel.add(supplierNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 150, 30));

        supplierIDLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supplierIDLbl.setText("Supplier Id");
        InnerPanel.add(supplierIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, 30));

        supplierIDTxt.setEditable(false);
        supplierIDTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        supplierIDTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supplierIDTxt.setOpaque(false);
        InnerPanel.add(supplierIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 230, 30));

        soldDateTxt.setEditable(false);
        soldDateTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        soldDateTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        soldDateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        soldDateTxt.setOpaque(false);
        InnerPanel.add(soldDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 240, 30));

        customerIDTxt.setEditable(false);
        customerIDTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        customerIDTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerIDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        customerIDTxt.setOpaque(false);
        InnerPanel.add(customerIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 240, 30));

        soldInvNoTxt.setEditable(false);
        soldInvNoTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        soldInvNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        soldInvNoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        soldInvNoTxt.setOpaque(false);
        InnerPanel.add(soldInvNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 220, 30));

        soldDateLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        soldDateLbl.setText("Sold Date");
        InnerPanel.add(soldDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 100, 30));

        statusLbl.setForeground(new java.awt.Color(204, 0, 0));
        statusLbl.setText("Status");
        statusLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        InnerPanel.add(statusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 400, 30));

        mobileDetailsLbl1.setBackground(new java.awt.Color(255, 255, 255));
        mobileDetailsLbl1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81), 2), "Mobile Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Bright", 1, 14))); // NOI18N
        mobileDetailsLbl1.setOpaque(true);
        InnerPanel.add(mobileDetailsLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 930, 90));

        repeirDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        repeirDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81), 2), "Return Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Bright", 1, 14))); // NOI18N
        repeirDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnIDTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        returnIDTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        returnIDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        returnIDTxt.setOpaque(false);
        repeirDetailsPanel.add(returnIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 190, 30));

        returnIDLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        returnIDLbl.setText("Return ID");
        repeirDetailsPanel.add(returnIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        dateLBl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dateLBl.setText("Date");
        repeirDetailsPanel.add(dateLBl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 50, 30));

        dateTxt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        dateTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        dateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dateTxt.setOpaque(false);
        repeirDetailsPanel.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 220, 30));

        InnerPanel.add(repeirDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 930, 90));

        mobileDetailsLbl.setBackground(new java.awt.Color(255, 255, 255));
        mobileDetailsLbl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81), 2), "Mobile Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Bright", 1, 14))); // NOI18N
        mobileDetailsLbl.setOpaque(true);
        InnerPanel.add(mobileDetailsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 930, 260));

        allRetrunMobileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        allRetrunMobileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allRetrunMobileBtn.setText("All Return Mobiles");
        allRetrunMobileBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        allRetrunMobileBtn.setOpaque(true);
        allRetrunMobileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allRetrunMobileBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allRetrunMobileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allRetrunMobileBtnMouseExited(evt);
            }
        });
        InnerPanel.add(allRetrunMobileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 190, 40));

        jXPanel1.add(InnerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void warrentyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrentyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warrentyTxtActionPerformed

    private void clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseClicked
        statusLbl.setVisible(false);
        customerIDTxt.setText("");
        IMEINoTxt.setText("");
        customerNameTxt.setText("");
        supplierIDTxt.setText("");
        supplierNameTxt.setText("");
        soldDateTxt.setText("");
        soldInvNoTxt.setText("");
        warrentyTxt.setText("");
    }//GEN-LAST:event_clearBtnMouseClicked

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        String returnId = returnIDTxt.getText();
        String IMEINo = IMEINoTxt.getText();
        String curDate = dateTxt.getText();
        String soldDate = soldDateTxt.getText();
        String warrenty = statusLbl.getText();
        String issue = issueTxt.getText();
        String customerId = customerIDTxt.getText();
        String supplierId = supplierIDTxt.getText();
        String soldInvId = soldInvNoTxt.getText();

        if (IMEINo.trim().isEmpty()) {
            return;
        }
        if (customerId.isEmpty()) {
            return;
        }
        if (issue.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mention the issue type");
            return;
        }

        ReturnMobileDTO returnMobileDTO = new ReturnMobileDTO(returnId, IMEINo, curDate, soldDate, warrenty, issue, customerId, supplierId, soldInvId);

        try {
            boolean isAdded = ReturnMobileController.addReturnMobile(returnMobileDTO);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Successfully Added");
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReturnMobilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveBtnMouseClicked

    private void IMEINoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMEINoTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = IMEINoTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_IMEINoTxtKeyTyped

    private void IMEINoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMEINoTxtActionPerformed
        String IMEINo = IMEINoTxt.getText();
        try {
            CustomDTO returnMobileDetails = ReturnMobileController.getReturnMobileDetails(IMEINo);
            if (returnMobileDetails == null) {

                String content = "Invalid IMEI No input";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
                return;
            }

            int warranty = returnMobileDetails.getWarrentyPeriod();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String soldDate = returnMobileDetails.getSoldInvoiceDate();
            String curDate = dateTxt.getText();

            try {
                Date date1 = dateFormat.parse(soldDate);
                Date date2 = dateFormat.parse(curDate);
                long diff = date2.getTime() - date1.getTime();
                System.out.println("Days: " + TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS));
                long months = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS) / 30;
                System.out.println("Months :" + months);

                if (months >= warranty) {
                    statusLbl.setVisible(true);
                    statusLbl.setText("Expired");
                } else {
                    statusLbl.setVisible(true);
                    statusLbl.setText("Valid");
                }

            } catch (ParseException e) {
                e.printStackTrace();
            }

            customerIDTxt.setText(returnMobileDetails.getCustomerId());
            customerNameTxt.setText(returnMobileDetails.getCustomerName());
            supplierIDTxt.setText(returnMobileDetails.getSupplierId());
            supplierNameTxt.setText(returnMobileDetails.getSupplierName());
            soldDateTxt.setText(returnMobileDetails.getSoldInvoiceDate());
            soldInvNoTxt.setText(returnMobileDetails.getSoldInvoiceNo());
            warrentyTxt.setText(String.valueOf(returnMobileDetails.getWarrentyPeriod()));

        } catch (Exception ex) {
            Logger.getLogger(ReturnMobilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IMEINoTxtActionPerformed

    private void saveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseEntered
        saveBtn.setBackground(new Color(23, 114, 81));
        saveBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_saveBtnMouseEntered

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        saveBtn.setBackground(new Color(255, 255, 255));
        saveBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_saveBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 14, 65));
        clearBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 255, 255));
        clearBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_clearBtnMouseExited

    private void allRetrunMobileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allRetrunMobileBtnMouseClicked
        ViewAllReturnMobiles mobiles = new ViewAllReturnMobiles(null, true);
        mobiles.setVisible(true);
    }//GEN-LAST:event_allRetrunMobileBtnMouseClicked

    private void supplierNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTxtActionPerformed

    private void allRetrunMobileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allRetrunMobileBtnMouseEntered
        allRetrunMobileBtn.setBackground(new Color(23, 114, 81));
        allRetrunMobileBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_allRetrunMobileBtnMouseEntered

    private void allRetrunMobileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allRetrunMobileBtnMouseExited
        allRetrunMobileBtn.setBackground(new Color(255, 255, 255));
        allRetrunMobileBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_allRetrunMobileBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMEINILbl;
    private javax.swing.JTextField IMEINoTxt;
    private org.jdesktop.swingx.JXPanel InnerPanel;
    private org.jdesktop.swingx.JXLabel Title_lbl;
    private org.jdesktop.swingx.JXLabel allRetrunMobileBtn;
    private org.jdesktop.swingx.JXLabel clearBtn;
    private javax.swing.JLabel custmerIDLbl;
    private javax.swing.JTextField customerIDTxt;
    private javax.swing.JLabel customerNameLbl;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JLabel dateLBl;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel issueLbl;
    private javax.swing.JTextField issueTxt;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel mobileDetailsLbl;
    private org.jdesktop.swingx.JXLabel mobileDetailsLbl1;
    private org.jdesktop.swingx.JXPanel repeirDetailsPanel;
    private javax.swing.JLabel returnIDLbl;
    private javax.swing.JTextField returnIDTxt;
    private org.jdesktop.swingx.JXLabel saveBtn;
    private javax.swing.JLabel soldDateLbl;
    private javax.swing.JTextField soldDateTxt;
    private javax.swing.JLabel soldInvNoLbl;
    private javax.swing.JTextField soldInvNoTxt;
    private org.jdesktop.swingx.JXLabel statusLbl;
    private javax.swing.JLabel supplierIDLbl;
    private javax.swing.JTextField supplierIDTxt;
    private javax.swing.JLabel supplierNameLbl;
    private javax.swing.JTextField supplierNameTxt;
    private javax.swing.JLabel warrantyLbl;
    private javax.swing.JTextField warrentyTxt;
    // End of variables declaration//GEN-END:variables

    private void LoadCurrentDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String curDate = dateFormat.format(date);
        System.out.println(curDate);
        dateTxt.setText(curDate);
    }
}
