/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import com.project.mobileshop.controller.BatchController;
import com.project.mobileshop.controller.ModelController;
import com.project.mobileshop.core.dto.BatchDTO;
import com.project.mobileshop.core.dto.ModelDTO;
import com.project.mobileshop.util.Validation;
import com.project.mobileshop.view.ProfitPanel;
import com.project.mobileshop.view.StockMoreDetailDialog;
import com.project.mobileshop.view.stockBatchDetailsDialog;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class StockPanel extends javax.swing.JPanel {

    /**
     * Creates new form StockPanel
     */
    public StockPanel() {
        initComponents();
        LoadPanel();
        start();
    }

    
    public void start(){
        stockBtn.setFont(new Font("", 1, 24));
        stockBtn.setBackground(new Color(23, 114, 81));
        stockBtn.setForeground(new Color(255, 255, 255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StockBackPanel = new org.jdesktop.swingx.JXPanel();
        addCurrentStockBtn = new org.jdesktop.swingx.JXLabel();
        stockBtn = new org.jdesktop.swingx.JXLabel();
        titlelbl = new org.jdesktop.swingx.JXLabel();
        stockMainPanel = new org.jdesktop.swingx.JXPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StockBackPanel.setOpaque(false);
        StockBackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCurrentStockBtn.setBackground(new java.awt.Color(255, 255, 204));
        addCurrentStockBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addCurrentStockBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCurrentStockBtn.setText("Calculations");
        addCurrentStockBtn.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        addCurrentStockBtn.setOpaque(true);
        addCurrentStockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCurrentStockBtnMouseClicked(evt);
            }
        });
        StockBackPanel.add(addCurrentStockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 260, 40));

        stockBtn.setBackground(new java.awt.Color(255, 255, 204));
        stockBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stockBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockBtn.setText("Stock");
        stockBtn.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        stockBtn.setOpaque(true);
        stockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockBtnMouseEntered(evt);
            }
        });
        stockBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockBtnKeyPressed(evt);
            }
        });
        StockBackPanel.add(stockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, 40));

        titlelbl.setBackground(new java.awt.Color(0, 0, 0));
        titlelbl.setOpaque(true);
        StockBackPanel.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 60));

        stockMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        StockBackPanel.add(stockMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1060, 620));

        add(StockBackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void addCurrentStockBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCurrentStockBtnMouseClicked
        addCurrentStockBtn.setBackground(new Color(23, 114, 81));
        addCurrentStockBtn.setForeground(new Color(255, 255, 255));

        stockBtn.setBackground(new Color(255, 255, 204));
        stockBtn.setForeground(new Color(0, 0, 0));

        ProfitPanel addCurrentStockPanel = new ProfitPanel();
        stockMainPanel.removeAll();
        stockMainPanel.add(addCurrentStockPanel);
        stockMainPanel.revalidate();
        stockMainPanel.repaint();
        stockMainPanel.setVisible(true);
    }//GEN-LAST:event_addCurrentStockBtnMouseClicked

    private void stockBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockBtnKeyPressed

    private void stockBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtnMouseClicked
        stockBtn.setBackground(new Color(23, 114, 81));
        stockBtn.setForeground(new Color(255, 255, 255));

        addCurrentStockBtn.setBackground(new Color(255, 255, 204));
        addCurrentStockBtn.setForeground(new Color(0, 0, 0));

        Stock stock = new Stock();
        stockMainPanel.removeAll();
        stockMainPanel.add(stock);
        stockMainPanel.revalidate();
        stockMainPanel.repaint();
        stockMainPanel.setVisible(true);


    }//GEN-LAST:event_stockBtnMouseClicked

    private void stockBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stockBtnMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel StockBackPanel;
    private org.jdesktop.swingx.JXLabel addCurrentStockBtn;
    private org.jdesktop.swingx.JXLabel stockBtn;
    private org.jdesktop.swingx.JXPanel stockMainPanel;
    private org.jdesktop.swingx.JXLabel titlelbl;
    // End of variables declaration//GEN-END:variables

    private void LoadPanel() {
        Stock stock = new Stock();
        stockMainPanel.removeAll();
        stockMainPanel.add(stock);
        stockMainPanel.revalidate();
        stockMainPanel.repaint();
        stockMainPanel.setVisible(true);
    }
}
