/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.panels;

import com.project.mobileshop.controller.SupplierController;
import com.project.mobileshop.core.dto.SupplierDTO;
import com.project.mobileshop.view.EditSupplierDialog;
import com.project.mobileshop.view.AddNewSupplierDialog;
import com.project.mobileshop.view.JoptionMessageDialog;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class SupplierPanel extends javax.swing.JPanel {

    /**
     * Creates new form Supplier
     */
    public SupplierPanel() {
        initComponents();
        LoadAllSuppliers();
    }

    public void LoadAllSuppliers() {
        try {
            ArrayList<SupplierDTO> allSuppliers = SupplierController.getAllSuppliers();

            dtm = (DefaultTableModel) viewSupplierInfoTable.getModel();
            dtm.setRowCount(0);

            if (allSuppliers != null) {
                for (SupplierDTO s : allSuppliers) {
                    Object[] row = {s.getSupplierId(), s.getSupplierName(), s.getNICno(), s.getContactNo(), s.getCompany(), s.getAddress()};
                    dtm.addRow(row);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierBackPanel = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewSupplierInfoTable = new org.jdesktop.swingx.JXTable();
        addNewSupplierBt = new org.jdesktop.swingx.JXLabel();
        editCustomerBt = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        supNameTxt = new org.jdesktop.swingx.JXSearchField();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        companyTxt = new org.jdesktop.swingx.JXSearchField();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SupplierBackPanel.setBackground(new java.awt.Color(255, 255, 255));
        SupplierBackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("View Supplier Info");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        SupplierBackPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 270, 40));

        viewSupplierInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "NIC No", "Contact No", "Company", "Address"
            }
        ));
        viewSupplierInfoTable.setColumnMargin(3);
        viewSupplierInfoTable.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        viewSupplierInfoTable.setGridColor(new java.awt.Color(0, 0, 0));
        viewSupplierInfoTable.setRowHeight(25);
        jScrollPane1.setViewportView(viewSupplierInfoTable);

        SupplierBackPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1000, 370));

        addNewSupplierBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addNewSupplierBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNewSupplierBt.setText("Add New");
        addNewSupplierBt.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        addNewSupplierBt.setOpaque(true);
        addNewSupplierBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewSupplierBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewSupplierBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewSupplierBtMouseExited(evt);
            }
        });
        SupplierBackPanel.add(addNewSupplierBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 120, 40));

        editCustomerBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editCustomerBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editCustomerBt.setText("Edit ");
        editCustomerBt.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        editCustomerBt.setOpaque(true);
        editCustomerBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editCustomerBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editCustomerBtMouseExited(evt);
            }
        });
        SupplierBackPanel.add(editCustomerBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, 110, 40));

        jXLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel5.setText("Company");
        jXLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        SupplierBackPanel.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 170, 30));

        supNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supNameTxtActionPerformed(evt);
            }
        });
        supNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                supNameTxtKeyTyped(evt);
            }
        });
        SupplierBackPanel.add(supNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 30));

        jXLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel2.setText("Supplier Name");
        jXLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        SupplierBackPanel.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 30));

        companyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        companyTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        companyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTxtActionPerformed(evt);
            }
        });
        SupplierBackPanel.add(companyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 180, 30));

        jXLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 114, 81), 2), "Search By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gadugi", 1, 18), new java.awt.Color(23, 114, 81))); // NOI18N
        jXLabel3.setOpaque(true);
        SupplierBackPanel.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1010, 80));

        add(SupplierBackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void addNewSupplierBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewSupplierBtMouseClicked
        AddNewSupplierDialog supplier = new AddNewSupplierDialog(null, true);
        supplier.setVisible(true);
    }//GEN-LAST:event_addNewSupplierBtMouseClicked

    private void editCustomerBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtMouseEntered
        editCustomerBt.setBackground(new Color(23, 114, 81));
        editCustomerBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_editCustomerBtMouseEntered

    private void editCustomerBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtMouseExited
        editCustomerBt.setBackground(new Color(255, 255, 255));
        editCustomerBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_editCustomerBtMouseExited

    private void editCustomerBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerBtMouseClicked
        if (viewSupplierInfoTable.getSelectedRow() == -1) {
            //JOptionPane.showMessageDialog(this, "Select a supplier");
            String content = "Select a supplier";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }
        int selectedRow = viewSupplierInfoTable.getSelectedRow();
        SupplierDTO supplierDTO = new SupplierDTO();

        supplierDTO.setSupplierId(viewSupplierInfoTable.getValueAt(selectedRow, 0).toString());
        supplierDTO.setSupplierName(viewSupplierInfoTable.getValueAt(selectedRow, 1).toString());
        supplierDTO.setNICno(viewSupplierInfoTable.getValueAt(selectedRow, 2).toString());
        supplierDTO.setContactNo(Integer.parseInt(viewSupplierInfoTable.getValueAt(selectedRow, 3).toString()));
        supplierDTO.setCompany(viewSupplierInfoTable.getValueAt(selectedRow, 4).toString());
        supplierDTO.setAddress(viewSupplierInfoTable.getValueAt(selectedRow, 5).toString());

        EditSupplierDialog editSupplier = new EditSupplierDialog(null, true);
        editSupplier.getSupplierDetails(supplierDTO);
        editSupplier.setVisible(true);
    }//GEN-LAST:event_editCustomerBtMouseClicked

    private void supNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supNameTxtActionPerformed
        String supplierName = supNameTxt.getText();
        if (supplierName.equals("")) {
            LoadAllSuppliers();
        }
        try {
            SupplierDTO name = SupplierController.serachFromName(supplierName);
            if (name != null) {
                dtm = (DefaultTableModel) viewSupplierInfoTable.getModel();
                dtm.setRowCount(0);
                Object[] row = {name.getSupplierId(), name.getSupplierName(), name.getNICno(), name.getContactNo(), name.getCompany(), name.getAddress()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supNameTxtActionPerformed

    private void companyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTxtActionPerformed
        String company = companyTxt.getText();
        if (company.equals("")) {
            LoadAllSuppliers();
        }
        try {
            SupplierDTO name = SupplierController.serachFromCompany(company);
            if (name != null) {
                dtm = (DefaultTableModel) viewSupplierInfoTable.getModel();
                dtm.setRowCount(0);
                Object[] row = {name.getSupplierId(), name.getSupplierName(), name.getNICno(), name.getContactNo(), name.getCompany(), name.getAddress()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_companyTxtActionPerformed

    private void supNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supNameTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = supNameTxt.getText();
        if (Character.isDigit(keyChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_supNameTxtKeyTyped

    private void addNewSupplierBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewSupplierBtMouseEntered
        addNewSupplierBt.setBackground(new Color(23, 114, 81));
        addNewSupplierBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addNewSupplierBtMouseEntered

    private void addNewSupplierBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewSupplierBtMouseExited
        addNewSupplierBt.setBackground(new Color(255, 255, 255));
        addNewSupplierBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addNewSupplierBtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel SupplierBackPanel;
    private org.jdesktop.swingx.JXLabel addNewSupplierBt;
    private org.jdesktop.swingx.JXSearchField companyTxt;
    private org.jdesktop.swingx.JXLabel editCustomerBt;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXSearchField supNameTxt;
    private org.jdesktop.swingx.JXTable viewSupplierInfoTable;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel dtm = null;
}
