/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.BatchController;
import com.project.mobileshop.core.dto.BatchDTO;
import com.project.mobileshop.panels.AddGRN;
import java.awt.Color;
import java.math.BigDecimal;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class AddBatchDialog extends javax.swing.JDialog {

    /**
     * Creates new form BatchDialog
     */
    public AddBatchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0.7f));

    }

    public void LoadRelavantBatches(String modelNo, String modelName) throws Exception {
        modelNoTxt.setText(modelNo);
        modelNameTxt.setText(modelName);

        DefaultTableModel dtm = (DefaultTableModel) batchDetailsTable.getModel();

        ArrayList<BatchDTO> allSelectedBatches = BatchController.modelBatch(modelNo);
        for (BatchDTO a : allSelectedBatches) {
            String batchNo = a.getBatchNo();
            BigDecimal originalPrice = a.getOriginalPrice();
            BigDecimal sellingPrice = a.getSellingPrice();
            int qty = a.getQty();

            Object[] row = {batchNo, originalPrice, sellingPrice, qty};
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        backPanel = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        closeBtn = new org.jdesktop.swingx.JXLabel();
        batchNoLbl = new org.jdesktop.swingx.JXLabel();
        batchNoLbl1 = new org.jdesktop.swingx.JXLabel();
        modelNameTxt = new org.jdesktop.swingx.JXTextField();
        modelNoLbl = new org.jdesktop.swingx.JXLabel();
        modelNoTxt = new org.jdesktop.swingx.JXTextField();
        okBtn = new org.jdesktop.swingx.JXLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchDetailsTable = new org.jdesktop.swingx.JXTable();
        closeBtn1 = new org.jdesktop.swingx.JXLabel();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("Batch Numbers");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        backPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 250, 30));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        backPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 40));

        batchNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batchNoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/view all batchs title bar.jpg"))); // NOI18N
        batchNoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 28)); // NOI18N
        backPanel.add(batchNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        batchNoLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batchNoLbl1.setText("Model Name");
        batchNoLbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        backPanel.add(batchNoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 30));

        modelNameTxt.setEditable(false);
        modelNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNameTxt.setOpaque(false);
        backPanel.add(modelNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 180, 30));

        modelNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelNoLbl.setText("Model No");
        modelNoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        backPanel.add(modelNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 90, 30));

        modelNoTxt.setEditable(false);
        modelNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNoTxt.setOpaque(false);
        backPanel.add(modelNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 190, 30));

        okBtn.setBackground(new java.awt.Color(255, 255, 255));
        okBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        okBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okBtn.setText("OK");
        okBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        okBtn.setOpaque(true);
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okBtnMouseExited(evt);
            }
        });
        backPanel.add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 90, 30));

        batchDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch No", "Original Price", "SellingPrice", "Qty"
            }
        ));
        batchDetailsTable.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(batchDetailsTable);

        backPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 690, 180));

        closeBtn1.setBackground(new java.awt.Color(255, 255, 255));
        closeBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        closeBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn1.setText("Close");
        closeBtn1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        closeBtn1.setOpaque(true);
        closeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtn1MouseExited(evt);
            }
        });
        backPanel.add(closeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 90, 30));

        getContentPane().add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 790, 450));

        setBounds(0, 90, 1370, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        /* String newBatchNo = modelNameTxt.getText();
         String modelNo = modelNoTxt.getText();
        
        
        
         AddGRN addGRN=new AddGRN();
        
         addGRN.setNewBatchNo(newBatchNo);
        
         dispose();*/
        dispose();
    }//GEN-LAST:event_okBtnMouseClicked

    private void closeBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseClicked
        dispose();
    }//GEN-LAST:event_closeBtn1MouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption red.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseExited

    private void okBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseEntered
        okBtn.setBackground(new Color(23, 114, 81));
        okBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_okBtnMouseEntered

    private void okBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseExited
        okBtn.setBackground(new Color(255, 255, 255));
        okBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_okBtnMouseExited

    private void closeBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseEntered
        closeBtn1.setBackground(new Color(255, 14, 65));
        closeBtn1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_closeBtn1MouseEntered

    private void closeBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseExited
        closeBtn1.setBackground(new Color(255, 255, 255));
        closeBtn1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_closeBtn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBatchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBatchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBatchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBatchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBatchDialog dialog = new AddBatchDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel backPanel;
    private org.jdesktop.swingx.JXTable batchDetailsTable;
    private org.jdesktop.swingx.JXLabel batchNoLbl;
    private org.jdesktop.swingx.JXLabel batchNoLbl1;
    private org.jdesktop.swingx.JXLabel closeBtn;
    private org.jdesktop.swingx.JXLabel closeBtn1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTextField modelNameTxt;
    private org.jdesktop.swingx.JXLabel modelNoLbl;
    private org.jdesktop.swingx.JXTextField modelNoTxt;
    private org.jdesktop.swingx.JXLabel okBtn;
    // End of variables declaration//GEN-END:variables
}
