/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import java.awt.Color;

/**
 *
 * @author Janitha Dhananjaya
 */
public class AddGRNItemMessageDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddGRNItrmDislog
     */
    public AddGRNItemMessageDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0.6f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new org.jdesktop.swingx.JXPanel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        OKBtn = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel6.setText("Message");
        jXLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        backPanel.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Joption tool.jpg"))); // NOI18N
        jXLabel1.setOpaque(true);
        backPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 50));

        jXLabel5.setText("Now should be added Items of the GRN");
        jXLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        backPanel.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 380, 30));

        jXLabel4.setText("GRN is successfully added. ");
        jXLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        backPanel.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 270, 30));

        OKBtn.setBackground(new java.awt.Color(255, 255, 255));
        OKBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 216)));
        OKBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OKBtn.setText("OK");
        OKBtn.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        OKBtn.setOpaque(true);
        OKBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OKBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OKBtnMouseExited(evt);
            }
        });
        backPanel.add(OKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, 40));

        jXLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel3.setOpaque(true);
        backPanel.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        setBounds(0, 90, 1370, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKBtnMouseClicked
        OKBtn.setBackground(new Color(9, 177, 177));
        this.dispose();
        
    }//GEN-LAST:event_OKBtnMouseClicked

    private void OKBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKBtnMouseEntered
        OKBtn.setBackground(new Color(33, 177, 125));
    }//GEN-LAST:event_OKBtnMouseEntered

    private void OKBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKBtnMouseExited
       OKBtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_OKBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddGRNItemMessageDialog dialog = new AddGRNItemMessageDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel OKBtn;
    private org.jdesktop.swingx.JXPanel backPanel;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    // End of variables declaration//GEN-END:variables
}
