/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.BatchController;
import com.project.mobileshop.controller.MobileDetailController;
import com.project.mobileshop.core.dto.BatchDTO;
import com.project.mobileshop.core.dto.GRNDTO;
import com.project.mobileshop.core.dto.MobileDetailDTO;
import com.project.mobileshop.core.dto.ModelDTO;
import com.project.mobileshop.util.Validation;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class AddGRNItemDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddGRNItemDialog
     */
    public AddGRNItemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addBtn.setEnabled(false);
        nextItemBtn.setEnabled(false);
    }

    public void getModelData(ModelDTO modelDTO, String GRNno, String batchNo) {
        this.getItem(modelDTO, GRNno, batchNo);
    }

    public void getItem(ModelDTO modelDTO, String GRNno, String batchNo) {
        brandTxt.setText(modelDTO.getBrand());
        model_name_txt.setText(modelDTO.getModelName());
        batchNoTxt.setText(batchNo);
        QtyTxt.setText(String.valueOf(modelDTO.getQtyOnHand()));
        modelNoTxt.setText(modelDTO.getModelNo());
        GRNIDtxt.setText(GRNno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new org.jdesktop.swingx.JXLabel();
        GRNIDtxt = new javax.swing.JTextField();
        GRNnoLbl = new javax.swing.JLabel();
        imodel_name_lbl = new javax.swing.JLabel();
        model_name_txt = new javax.swing.JTextField();
        deliveredQtyLbl = new javax.swing.JLabel();
        QtyTxt = new javax.swing.JTextField();
        modelNoLbl = new javax.swing.JLabel();
        modelNoTxt = new javax.swing.JTextField();
        batchNolbl = new javax.swing.JLabel();
        batchNoTxt = new javax.swing.JTextField();
        brandTxt = new javax.swing.JTextField();
        brandLbl = new javax.swing.JLabel();
        IMEInoLbl = new javax.swing.JLabel();
        colourlbl = new javax.swing.JLabel();
        color_txt = new javax.swing.JTextField();
        IMEI_No_txt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        boarder1Lbl1 = new org.jdesktop.swingx.JXLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemTable = new org.jdesktop.swingx.JXTable();
        boarder1Lbl2 = new org.jdesktop.swingx.JXLabel();
        addItemBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        nextItemBtn = new javax.swing.JButton();
        boarder1Lbl3 = new org.jdesktop.swingx.JXLabel();
        addBtn = new javax.swing.JButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setForeground(new java.awt.Color(51, 51, 51));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Add Item");
        titleLbl.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        getContentPane().add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 170, 40));

        GRNIDtxt.setEditable(false);
        GRNIDtxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNIDtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        GRNIDtxt.setOpaque(false);
        GRNIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNIDtxtActionPerformed(evt);
            }
        });
        getContentPane().add(GRNIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 30));

        GRNnoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNnoLbl.setText("GRN ID");
        getContentPane().add(GRNnoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 30));

        imodel_name_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        imodel_name_lbl.setText("Model Name");
        getContentPane().add(imodel_name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 130, 30));

        model_name_txt.setEditable(false);
        model_name_txt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        model_name_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        model_name_txt.setOpaque(false);
        model_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_name_txtActionPerformed(evt);
            }
        });
        getContentPane().add(model_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 170, 30));

        deliveredQtyLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        deliveredQtyLbl.setText("Delivered Qty");
        getContentPane().add(deliveredQtyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, 30));

        QtyTxt.setEditable(false);
        QtyTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        QtyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        QtyTxt.setOpaque(false);
        QtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyTxtActionPerformed(evt);
            }
        });
        getContentPane().add(QtyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 150, 30));

        modelNoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNoLbl.setText("Model No");
        getContentPane().add(modelNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 30));

        modelNoTxt.setEditable(false);
        modelNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNoTxt.setOpaque(false);
        modelNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(modelNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 30));

        batchNolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        batchNolbl.setText("Batch no");
        getContentPane().add(batchNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 80, 30));

        batchNoTxt.setEditable(false);
        batchNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        batchNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        batchNoTxt.setOpaque(false);
        batchNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(batchNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 170, 30));

        brandTxt.setEditable(false);
        brandTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        brandTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        brandTxt.setOpaque(false);
        brandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTxtActionPerformed(evt);
            }
        });
        getContentPane().add(brandTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 150, 30));

        brandLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        brandLbl.setText("Brand");
        getContentPane().add(brandLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 60, 30));

        IMEInoLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        IMEInoLbl.setText("IMEI No");
        getContentPane().add(IMEInoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 30));

        colourlbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        colourlbl.setText("Colour");
        getContentPane().add(colourlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 70, 30));

        color_txt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        color_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        color_txt.setOpaque(false);
        color_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_txtActionPerformed(evt);
            }
        });
        color_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                color_txtKeyTyped(evt);
            }
        });
        getContentPane().add(color_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 200, 30));

        IMEI_No_txt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        IMEI_No_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        IMEI_No_txt.setOpaque(false);
        IMEI_No_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMEI_No_txtActionPerformed(evt);
            }
        });
        IMEI_No_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IMEI_No_txtKeyTyped(evt);
            }
        });
        getContentPane().add(IMEI_No_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 250, 30));

        statusLbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        statusLbl.setText("Status");
        getContentPane().add(statusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 60, 30));

        statusTxt.setEditable(false);
        statusTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        statusTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        statusTxt.setOpaque(false);
        statusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTxtActionPerformed(evt);
            }
        });
        getContentPane().add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 160, 30));

        boarder1Lbl1.setBackground(new java.awt.Color(255, 255, 255));
        boarder1Lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        boarder1Lbl1.setOpaque(true);
        getContentPane().add(boarder1Lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1000, 120));

        ItemTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IMEI No", "Colour", "Status"
            }
        ));
        jScrollPane2.setViewportView(ItemTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 770, 240));

        boarder1Lbl2.setBackground(new java.awt.Color(255, 255, 255));
        boarder1Lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        boarder1Lbl2.setOpaque(true);
        getContentPane().add(boarder1Lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1000, 70));

        addItemBtn.setBackground(new java.awt.Color(255, 255, 255));
        addItemBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addItemBtn.setText("Add Items");
        addItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addItemBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addItemBtnMouseExited(evt);
            }
        });
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addItemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 130, 50));

        removeBtn.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeBtnMouseExited(evt);
            }
        });
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 130, 50));

        nextItemBtn.setBackground(new java.awt.Color(255, 255, 255));
        nextItemBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        nextItemBtn.setText("Next Item");
        nextItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextItemBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextItemBtnMouseExited(evt);
            }
        });
        nextItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextItemBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextItemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, 40));

        boarder1Lbl3.setBackground(new java.awt.Color(255, 255, 255));
        boarder1Lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        boarder1Lbl3.setOpaque(true);
        getContentPane().add(boarder1Lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 200, 230));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 100, 40));

        jXLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel1.setOpaque(true);
        getContentPane().add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        setBounds(310, 90, 1060, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void GRNIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRNIDtxtActionPerformed

    private void model_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_name_txtActionPerformed

    private void QtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyTxtActionPerformed

    private void modelNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxtActionPerformed

    }//GEN-LAST:event_modelNoTxtActionPerformed

    private void batchNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNoTxtActionPerformed


    }//GEN-LAST:event_batchNoTxtActionPerformed

    private void color_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_txtActionPerformed
        statusTxt.setText("not sell");

        String IEMIno = IMEI_No_txt.getText();
        String colour = color_txt.getText();
        String status = statusTxt.getText();

        if (!(IEMIno.isEmpty()) && !(colour.isEmpty()) && !(status.isEmpty())) {
            addBtn.setEnabled(true);

        }


    }//GEN-LAST:event_color_txtActionPerformed

    private void IMEI_No_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMEI_No_txtActionPerformed
        color_txt.requestFocus();
    }//GEN-LAST:event_IMEI_No_txtActionPerformed

    private void brandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTxtActionPerformed

    private void statusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTxtActionPerformed

    }//GEN-LAST:event_statusTxtActionPerformed

    private void IMEI_No_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMEI_No_txtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = IMEI_No_txt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
    }//GEN-LAST:event_IMEI_No_txtKeyTyped

    private void color_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_color_txtKeyTyped
        Validation.name(color_txt);
    }//GEN-LAST:event_color_txtKeyTyped

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        qty = Integer.parseInt(QtyTxt.getText());

        addBtnDisabled++;
        boolean equals = false;
        if (addBtnDisabled == qty) {
            equals = true;

        }

        DefaultTableModel dtm = (DefaultTableModel) ItemTable.getModel();
        Object[] row = {IMEI_No_txt.getText(), color_txt.getText(), statusTxt.getText()};
        dtm.addRow(row);

        IMEI_No_txt.setText("");
        color_txt.setText("");
        statusTxt.setText("");

        IMEI_No_txt.requestFocus();

        if (equals) {
            addBtn.setEnabled(false);
            IMEI_No_txt.setEditable(false);
            color_txt.setEditable(false);
            
            return;
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        addBtn.setBackground(new Color(23, 114, 81));
        addBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        addBtn.setBackground(new Color(255, 255, 255));
        addBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addBtnMouseExited

    private void nextItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextItemBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_nextItemBtnActionPerformed

    private void nextItemBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextItemBtnMouseEntered
        nextItemBtn.setBackground(new Color(23, 114, 81));
        nextItemBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_nextItemBtnMouseEntered

    private void nextItemBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextItemBtnMouseExited
        nextItemBtn.setBackground(new Color(255, 255, 255));
        nextItemBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_nextItemBtnMouseExited

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        String modelNo = modelNoTxt.getText();
        BatchDTO batchDTO = new BatchDTO();

        ArrayList<MobileDetailDTO> mobileList = new ArrayList<>();

        for (int i = 0; i < ItemTable.getRowCount(); i++) {
            MobileDetailDTO mobileDetailDTO = new MobileDetailDTO(
                    ItemTable.getValueAt(i, 0).toString(),
                    ItemTable.getValueAt(i, 1).toString(),
                    ItemTable.getValueAt(i, 2).toString(),
                    GRNIDtxt.getText(),
                    modelNoTxt.getText(),
                    batchNoTxt.getText());
            mobileList.add(mobileDetailDTO);
        }
        try {
            boolean isAdded = MobileDetailController.addMobiles(mobileList);
            if (isAdded) {
                String content = "Mobiles added Successfully";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
                addItemBtn.setEnabled(false);
                nextItemBtn.setEnabled(true);
            } else {
                String content = "ERROR!";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddGRNItemDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void addItemBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemBtnMouseEntered
        addItemBtn.setBackground(new Color(23, 114, 81));
        addItemBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addItemBtnMouseEntered

    private void addItemBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemBtnMouseExited
        addItemBtn.setBackground(new Color(255, 255, 255));
        addItemBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addItemBtnMouseExited

    private void removeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseEntered
        removeBtn.setBackground(new Color(255, 14, 65));
        removeBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_removeBtnMouseEntered

    private void removeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseExited
        removeBtn.setBackground(new Color(255, 255, 255));
        removeBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_removeBtnMouseExited

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed

        if (ItemTable.getSelectedRow() == -1) {
            String content = "Please select a IMEI no";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }
        int removeRow = ItemTable.getSelectedRow();
        addBtnDisabled--;
        DefaultTableModel dtm = (DefaultTableModel) ItemTable.getModel();
        dtm.removeRow(removeRow);

    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGRNItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddGRNItemDialog dialog = new AddGRNItemDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GRNIDtxt;
    private javax.swing.JLabel GRNnoLbl;
    private javax.swing.JTextField IMEI_No_txt;
    private javax.swing.JLabel IMEInoLbl;
    private org.jdesktop.swingx.JXTable ItemTable;
    private javax.swing.JTextField QtyTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JTextField batchNoTxt;
    private javax.swing.JLabel batchNolbl;
    private org.jdesktop.swingx.JXLabel boarder1Lbl1;
    private org.jdesktop.swingx.JXLabel boarder1Lbl2;
    private org.jdesktop.swingx.JXLabel boarder1Lbl3;
    private javax.swing.JLabel brandLbl;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JTextField color_txt;
    private javax.swing.JLabel colourlbl;
    private javax.swing.JLabel deliveredQtyLbl;
    private javax.swing.JLabel imodel_name_lbl;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JLabel modelNoLbl;
    private javax.swing.JTextField modelNoTxt;
    private javax.swing.JTextField model_name_txt;
    private javax.swing.JButton nextItemBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextField statusTxt;
    private org.jdesktop.swingx.JXLabel titleLbl;
    // End of variables declaration//GEN-END:variables
    private int addBtnDisabled = 0;
    private int selectedRow = 0;
    private int qty = 0;
}
