/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.CustomerController;
import com.project.mobileshop.core.dto.CustomerDTO;
import com.project.mobileshop.idgeneretor.IDGenerator;
import com.project.mobileshop.panels.OrderPanel;
import com.project.mobileshop.util.Validation;
import java.awt.Color;
import java.awt.Font;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Janitha Dhananjaya
 */
public class addNewCustomer extends javax.swing.JDialog {

    /**
     * Creates new form addNewCustomer
     */
    public addNewCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        generateCustomerID();
        setBackground(new Color(0, 0, 0, 0.6f));
    }

    public void generateCustomerID() {
        try {
            customerId.setText(IDGenerator.getNewID("customer", "customerId", "C"));
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewCustomerPanel = new org.jdesktop.swingx.JXPanel();
        titlelbl = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        closeBt = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        NICnoTxt = new org.jdesktop.swingx.JXTextField();
        customerNameTxt = new org.jdesktop.swingx.JXTextField();
        customerNamelbl = new org.jdesktop.swingx.JXLabel();
        NICnolbl = new org.jdesktop.swingx.JXLabel();
        contactNoTxt = new org.jdesktop.swingx.JXTextField();
        contactNolbl = new org.jdesktop.swingx.JXLabel();
        customerId = new org.jdesktop.swingx.JXTextField();
        customerIdlbl = new org.jdesktop.swingx.JXLabel();
        panelbackground = new org.jdesktop.swingx.JXPanel();
        addBt = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewCustomerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        addNewCustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl.setOpaque(false);
        titlelbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("Add Customer");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 28)); // NOI18N
        titlelbl.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 220, 30));

        closeBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png"))); // NOI18N
        closeBt.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        closeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtMouseExited(evt);
            }
        });
        titlelbl.add(closeBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 30));

        jXLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/date & time back.jpg"))); // NOI18N
        titlelbl.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 910, 50));

        addNewCustomerPanel.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        NICnoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        NICnoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        NICnoTxt.setOpaque(false);
        NICnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICnoTxtActionPerformed(evt);
            }
        });
        NICnoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NICnoTxtKeyTyped(evt);
            }
        });
        addNewCustomerPanel.add(NICnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 200, 30));

        customerNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerNameTxt.setOpaque(false);
        customerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTxtActionPerformed(evt);
            }
        });
        customerNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerNameTxtKeyTyped(evt);
            }
        });
        addNewCustomerPanel.add(customerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 170, 30));

        customerNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerNamelbl.setText("Customer Name");
        customerNamelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addNewCustomerPanel.add(customerNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 150, 30));

        NICnolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NICnolbl.setText("NIC No");
        NICnolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addNewCustomerPanel.add(NICnolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 90, 30));

        contactNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        contactNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        contactNoTxt.setOpaque(false);
        contactNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTxtActionPerformed(evt);
            }
        });
        contactNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactNoTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNoTxtKeyTyped(evt);
            }
        });
        addNewCustomerPanel.add(contactNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));

        contactNolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactNolbl.setText("Contact No");
        contactNolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addNewCustomerPanel.add(contactNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 30));

        customerId.setEditable(false);
        customerId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerId.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        customerId.setMargin(new java.awt.Insets(0, 0, 2, 0));
        customerId.setOpaque(false);
        customerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdActionPerformed(evt);
            }
        });
        customerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerIdKeyTyped(evt);
            }
        });
        addNewCustomerPanel.add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, 30));

        customerIdlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerIdlbl.setText("Customer ID");
        customerIdlbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addNewCustomerPanel.add(customerIdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        panelbackground.setBackground(new java.awt.Color(255, 255, 255));
        panelbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBt.setDisplayedMnemonic('A');
        addBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBt.setText("Add");
        addBt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        addBt.setOpaque(true);
        addBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtMouseExited(evt);
            }
        });
        panelbackground.add(addBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, 40));

        addNewCustomerPanel.add(panelbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 320));

        getContentPane().add(addNewCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 720, 350));

        setBounds(0, 90, 1370, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTxtActionPerformed
        contactNoTxt.requestFocus();
    }//GEN-LAST:event_customerNameTxtActionPerformed

    private void contactNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTxtActionPerformed
        NICnoTxt.requestFocus();
    }//GEN-LAST:event_contactNoTxtActionPerformed

    private void customerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdActionPerformed
        customerNameTxt.requestFocus();
    }//GEN-LAST:event_customerIdActionPerformed

    private void addBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseEntered
        addBt.setBackground(new Color(23, 114, 81));
        addBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addBtMouseEntered

    private void addBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseExited
        addBt.setBackground(new Color(255, 255, 255));
        addBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addBtMouseExited

    private void addBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseClicked
        String cutomerId = customerId.getText();
        String customerName = customerNameTxt.getText();
        String tel = contactNoTxt.getText();
        String NICno = NICnoTxt.getText();

        if (cutomerId.trim().isEmpty() || customerName.trim().isEmpty() || tel.trim().isEmpty() || NICno.trim().isEmpty()) {
            //JOptionPane.showMessageDialog(this, "Please fill all TextFields");
            String content = "Please fill all TextFields";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        int contactNo = Integer.parseInt(contactNoTxt.getText());

        CustomerDTO customerDTO = new CustomerDTO(cutomerId, customerName, contactNo, NICno);
        try {
            boolean result = CustomerController.addCustomer(customerDTO);
            if (result) {
                // JOptionPane.showMessageDialog(this, "Customer Added successfully..");
                String content = "Customer Added successfully..";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            } else {
                // JOptionPane.showMessageDialog(this, "Custmer not Added...");
                String content = "Custmer not Added...";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }
        } catch (SQLException ex) {
            Logger.getLogger(addNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(addNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addBtMouseClicked

    private void NICnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICnoTxtActionPerformed
        addBt.requestFocus();
    }//GEN-LAST:event_NICnoTxtActionPerformed

    private void customerIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIdKeyTyped

    }//GEN-LAST:event_customerIdKeyTyped

    private void customerNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNameTxtKeyTyped
        Validation.name(customerNameTxt);
    }//GEN-LAST:event_customerNameTxtKeyTyped

    private void contactNoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoTxtKeyPressed
        // 
    }//GEN-LAST:event_contactNoTxtKeyPressed

    private void NICnoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICnoTxtKeyTyped
        Validation.NIC(NICnoTxt);
    }//GEN-LAST:event_NICnoTxtKeyTyped

    private void closeBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBt.setIcon(imageIcon);

    }//GEN-LAST:event_closeBtMouseExited

    private void closeBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption red.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBt.setIcon(imageIcon);

    }//GEN-LAST:event_closeBtMouseEntered

    private void closeBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtMouseClicked
        OrderPanel orderPanel = new OrderPanel();

        dispose();
    }//GEN-LAST:event_closeBtMouseClicked

    private void contactNoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = contactNoTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
        if(IMEI.length()>9){
             evt.consume();
        }

    }//GEN-LAST:event_contactNoTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addNewCustomer dialog = new addNewCustomer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextField NICnoTxt;
    private org.jdesktop.swingx.JXLabel NICnolbl;
    private org.jdesktop.swingx.JXLabel addBt;
    private org.jdesktop.swingx.JXPanel addNewCustomerPanel;
    private org.jdesktop.swingx.JXLabel closeBt;
    private org.jdesktop.swingx.JXTextField contactNoTxt;
    private org.jdesktop.swingx.JXLabel contactNolbl;
    private org.jdesktop.swingx.JXTextField customerId;
    private org.jdesktop.swingx.JXLabel customerIdlbl;
    private org.jdesktop.swingx.JXTextField customerNameTxt;
    private org.jdesktop.swingx.JXLabel customerNamelbl;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXPanel panelbackground;
    private org.jdesktop.swingx.JXPanel titlelbl;
    // End of variables declaration//GEN-END:variables
}
