/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.SupplierController;
import com.project.mobileshop.core.dto.SupplierDTO;
import com.project.mobileshop.idgeneretor.IDGenerator;
import com.project.mobileshop.panels.OrderPanel;
import com.project.mobileshop.util.Validation;
import java.awt.Color;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Janitha Dhananjaya
 */
public class AddNewSupplierDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public AddNewSupplierDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        generateSupplierID();
        setBackground(new Color(0, 0, 0, 0.7f));
        supplierNameTxt.requestFocus();
    }

    public void generateSupplierID() {
        try {
            supplierIdTxt.setText(IDGenerator.getNewID("supplier", "supplierId", "C"));
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSupplierDialogPanel = new org.jdesktop.swingx.JXPanel();
        titlelPanel = new org.jdesktop.swingx.JXPanel();
        titlelbl = new org.jdesktop.swingx.JXLabel();
        closeBtn = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        dialogBackGroundPanel = new org.jdesktop.swingx.JXPanel();
        supplierIdTxt = new org.jdesktop.swingx.JXTextField();
        supplierIdlbl = new org.jdesktop.swingx.JXLabel();
        contaclNolbl = new org.jdesktop.swingx.JXLabel();
        contactNoTxt = new org.jdesktop.swingx.JXTextField();
        addresslbl = new org.jdesktop.swingx.JXLabel();
        addressTxt = new org.jdesktop.swingx.JXTextField();
        companylbl = new org.jdesktop.swingx.JXLabel();
        supplierNamelbl = new org.jdesktop.swingx.JXLabel();
        supplierNameTxt = new org.jdesktop.swingx.JXTextField();
        companyTxt = new org.jdesktop.swingx.JXTextField();
        NICnolbl = new org.jdesktop.swingx.JXLabel();
        NICnoTxt = new org.jdesktop.swingx.JXTextField();
        addBt = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSupplierDialogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelPanel.setOpaque(false);
        titlelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelbl.setText("Add New Supplier");
        titlelbl.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        titlelPanel.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 30));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        titlelPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, 30));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/date & time back.jpg"))); // NOI18N
        titlelPanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 1210, 50));

        addSupplierDialogPanel.add(titlelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        dialogBackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        dialogBackGroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dialogBackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierIdTxt.setEditable(false);
        supplierIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supplierIdTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supplierIdTxt.setMargin(new java.awt.Insets(0, 0, 2, 0));
        supplierIdTxt.setOpaque(false);
        dialogBackGroundPanel.add(supplierIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 180, 30));

        supplierIdlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierIdlbl.setText("Supplier ID");
        supplierIdlbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dialogBackGroundPanel.add(supplierIdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 30));

        contaclNolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contaclNolbl.setText("Contact No");
        contaclNolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dialogBackGroundPanel.add(contaclNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        contactNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        contactNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        contactNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTxtActionPerformed(evt);
            }
        });
        contactNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNoTxtKeyTyped(evt);
            }
        });
        dialogBackGroundPanel.add(contactNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 30));

        addresslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addresslbl.setText("Address");
        addresslbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dialogBackGroundPanel.add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));

        addressTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        addressTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        dialogBackGroundPanel.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, 30));

        companylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companylbl.setText("Company");
        companylbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dialogBackGroundPanel.add(companylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 90, 30));

        supplierNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierNamelbl.setText("Supplier Name");
        supplierNamelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dialogBackGroundPanel.add(supplierNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 140, 30));

        supplierNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supplierNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        supplierNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtActionPerformed(evt);
            }
        });
        supplierNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                supplierNameTxtKeyTyped(evt);
            }
        });
        dialogBackGroundPanel.add(supplierNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 190, 30));

        companyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        companyTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        companyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTxtActionPerformed(evt);
            }
        });
        dialogBackGroundPanel.add(companyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 190, 30));

        NICnolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NICnolbl.setText("NIC No");
        NICnolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        dialogBackGroundPanel.add(NICnolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 30));

        NICnoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        NICnoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        NICnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICnoTxtActionPerformed(evt);
            }
        });
        NICnoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NICnoTxtKeyTyped(evt);
            }
        });
        dialogBackGroundPanel.add(NICnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 190, 30));

        addBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBt.setText("Add");
        addBt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        addBt.setOpaque(true);
        addBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtMouseExited(evt);
            }
        });
        dialogBackGroundPanel.add(addBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 110, 40));

        addSupplierDialogPanel.add(dialogBackGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 320));

        getContentPane().add(addSupplierDialogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 720, 350));

        setBounds(0, 90, 1360, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void contactNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTxtActionPerformed
        NICnoTxt.requestFocus();
    }//GEN-LAST:event_contactNoTxtActionPerformed

    private void contactNoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoTxtKeyTyped
        char keyChar = evt.getKeyChar();
        String IMEI = contactNoTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
        if (IMEI.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_contactNoTxtKeyTyped

    private void supplierNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtActionPerformed
        contactNoTxt.requestFocus();
    }//GEN-LAST:event_supplierNameTxtActionPerformed

    private void supplierNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameTxtKeyTyped
        Validation.name(supplierNameTxt);
    }//GEN-LAST:event_supplierNameTxtKeyTyped

    private void NICnoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICnoTxtKeyTyped
        Validation.NIC(NICnoTxt);
    }//GEN-LAST:event_NICnoTxtKeyTyped

    private void addBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseClicked
        String supplierId = supplierIdTxt.getText();
        String supplierName = supplierNameTxt.getText();
        String address = addressTxt.getText();
        String company = companyTxt.getText();
        String NICno = NICnoTxt.getText();
        String telNo = contactNoTxt.getText();

        if (supplierId.trim().isEmpty() || supplierName.trim().isEmpty() || address.trim().isEmpty() || company.trim().isEmpty()
                || NICno.trim().isEmpty() || telNo.trim().isEmpty()) {
            String content = "Please Fill all Text Fields";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        int contactNo = Integer.parseInt(contactNoTxt.getText());

        SupplierDTO supplierDTO = new SupplierDTO(supplierId, supplierName, contactNo, address, company, NICno);

        try {
            boolean isAdded = SupplierController.addSupplier(supplierDTO);
            if (isAdded) {
                String content = "Supplier Added Successfuly";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);

                this.dispose();
                AddNewSupplierDialog newSupplierDialog = new AddNewSupplierDialog(null, true);
                newSupplierDialog.setVisible(true);
            } else {

                String content = "Supplier not Added";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewSupplierDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addBtMouseClicked

    private void addBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseEntered
        addBt.setBackground(new Color(23, 114, 81));
        addBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addBtMouseEntered

    private void addBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtMouseExited
        addBt.setBackground(new Color(255, 255, 255));
        addBt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addBtMouseExited

    private void NICnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICnoTxtActionPerformed
        addressTxt.requestFocus();
    }//GEN-LAST:event_NICnoTxtActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        companyTxt.requestFocus();
    }//GEN-LAST:event_addressTxtActionPerformed

    private void companyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTxtActionPerformed

    }//GEN-LAST:event_companyTxtActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption red.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplierDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewSupplierDialog dialog = new AddNewSupplierDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextField NICnoTxt;
    private org.jdesktop.swingx.JXLabel NICnolbl;
    private org.jdesktop.swingx.JXLabel addBt;
    private org.jdesktop.swingx.JXPanel addSupplierDialogPanel;
    private org.jdesktop.swingx.JXTextField addressTxt;
    private org.jdesktop.swingx.JXLabel addresslbl;
    private org.jdesktop.swingx.JXLabel closeBtn;
    private org.jdesktop.swingx.JXTextField companyTxt;
    private org.jdesktop.swingx.JXLabel companylbl;
    private org.jdesktop.swingx.JXLabel contaclNolbl;
    private org.jdesktop.swingx.JXTextField contactNoTxt;
    private org.jdesktop.swingx.JXPanel dialogBackGroundPanel;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXTextField supplierIdTxt;
    private org.jdesktop.swingx.JXLabel supplierIdlbl;
    private org.jdesktop.swingx.JXTextField supplierNameTxt;
    private org.jdesktop.swingx.JXLabel supplierNamelbl;
    private org.jdesktop.swingx.JXPanel titlelPanel;
    private org.jdesktop.swingx.JXLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
