/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.MobileDetailController;
import com.project.mobileshop.core.dto.MobileDetailDTO;
import com.project.mobileshop.core.dto.ModelDTO;
import java.awt.Color;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Janitha Dhananjaya
 */
public class EditIMEINoDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditIMEINoDialog
     */
    public EditIMEINoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0.7f));

    }

    public void getMobileDetails(ModelDTO modelDTO, MobileDetailDTO mobileDetailDTO) {
        modelNameTxt.setText(modelDTO.getModelName());
        modelNoTxt.setText(modelDTO.getModelNo());
        System.out.println(mobileDetailDTO.getIMEIno());
        IMEINoTxt.setText(mobileDetailDTO.getIMEIno());
        backUpIMEI = mobileDetailDTO.getIMEIno();
        coloutTxt.setText(mobileDetailDTO.getColur());
        batchNoTxt.setText(mobileDetailDTO.getBatchNo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateMobileIEMInobackPanel = new org.jdesktop.swingx.JXPanel();
        itemCodelbl = new org.jdesktop.swingx.JXLabel();
        IMEINoTxt = new org.jdesktop.swingx.JXTextField();
        iteNamelbl = new org.jdesktop.swingx.JXLabel();
        modelNameTxt = new org.jdesktop.swingx.JXTextField();
        saveBtn = new org.jdesktop.swingx.JXLabel();
        titlePanel = new org.jdesktop.swingx.JXPanel();
        closeBtn = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        itemCodelbl1 = new org.jdesktop.swingx.JXLabel();
        modelNoTxt = new org.jdesktop.swingx.JXTextField();
        itemCodelbl2 = new org.jdesktop.swingx.JXLabel();
        coloutTxt = new org.jdesktop.swingx.JXTextField();
        itemCodelbl3 = new org.jdesktop.swingx.JXLabel();
        batchNoTxt = new org.jdesktop.swingx.JXTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateMobileIEMInobackPanel.setBackground(new java.awt.Color(255, 255, 255));
        updateMobileIEMInobackPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateMobileIEMInobackPanel.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        updateMobileIEMInobackPanel.setPreferredSize(new java.awt.Dimension(720, 350));
        updateMobileIEMInobackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemCodelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl.setText("IMEI No");
        itemCodelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        updateMobileIEMInobackPanel.add(itemCodelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 30));

        IMEINoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        IMEINoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        IMEINoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMEINoTxtActionPerformed(evt);
            }
        });
        updateMobileIEMInobackPanel.add(IMEINoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, 30));

        iteNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iteNamelbl.setText("Model Name");
        iteNamelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        updateMobileIEMInobackPanel.add(iteNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 130, 30));

        modelNameTxt.setEditable(false);
        modelNameTxt.setBackground(new java.awt.Color(232, 232, 244));
        modelNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        modelNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        modelNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameTxtActionPerformed(evt);
            }
        });
        updateMobileIEMInobackPanel.add(modelNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 200, 30));

        saveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saveBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveBtn.setText("Save Changes");
        saveBtn.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        saveBtn.setOpaque(true);
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });
        updateMobileIEMInobackPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 180, 40));

        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        titlePanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jXLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel2.setText("Edit Mobile Details");
        jXLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        titlePanel.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 290, 30));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/date & time back.jpg"))); // NOI18N
        titlePanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 1070, 50));

        updateMobileIEMInobackPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        itemCodelbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl1.setText("Model No");
        itemCodelbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        updateMobileIEMInobackPanel.add(itemCodelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        modelNoTxt.setEditable(false);
        modelNoTxt.setBackground(new java.awt.Color(232, 232, 244));
        modelNoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        modelNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        modelNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxtActionPerformed(evt);
            }
        });
        updateMobileIEMInobackPanel.add(modelNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, 30));

        itemCodelbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl2.setText("Colour");
        itemCodelbl2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        updateMobileIEMInobackPanel.add(itemCodelbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 130, 30));

        coloutTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        coloutTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        coloutTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloutTxtActionPerformed(evt);
            }
        });
        updateMobileIEMInobackPanel.add(coloutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 190, 30));

        itemCodelbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl3.setText("Batch No");
        itemCodelbl3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        updateMobileIEMInobackPanel.add(itemCodelbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 30));

        batchNoTxt.setEditable(false);
        batchNoTxt.setBackground(new java.awt.Color(232, 232, 244));
        batchNoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        batchNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        batchNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNoTxtActionPerformed(evt);
            }
        });
        updateMobileIEMInobackPanel.add(batchNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 30));

        getContentPane().add(updateMobileIEMInobackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 780, 370));

        setBounds(0, 90, 1366, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void IMEINoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMEINoTxtActionPerformed
        coloutTxt.requestFocus();
    }//GEN-LAST:event_IMEINoTxtActionPerformed

    private void modelNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNameTxtActionPerformed

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        String IMEINo = IMEINoTxt.getText();
        String colur = coloutTxt.getText();
        String modelNO = modelNoTxt.getText();
        if (IMEINo.trim().isEmpty() || colur.trim().isEmpty()) {
            return;
        }
        MobileDetailDTO dTO = new MobileDetailDTO();
        dTO.setIMEIno(IMEINo);
        dTO.setColur(colur);
        dTO.setModelNo(modelNO);

        try {
            boolean isSuccessed = MobileDetailController.update(dTO, backUpIMEI);
            if (isSuccessed) {
                String content = "Saves Successfully";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            } else {
                String content = "ERROR!";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }
        } catch (Exception ex) {
            Logger.getLogger(EditIMEINoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption red.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseExited

    private void modelNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNoTxtActionPerformed

    private void coloutTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloutTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coloutTxtActionPerformed

    private void batchNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNoTxtActionPerformed

    private void saveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseEntered
        saveBtn.setBackground(new Color(23, 114, 81));
        saveBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_saveBtnMouseEntered

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        saveBtn.setBackground(new Color(255, 255, 255));
        saveBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_saveBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditIMEINoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditIMEINoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditIMEINoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditIMEINoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditIMEINoDialog dialog = new EditIMEINoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextField IMEINoTxt;
    private org.jdesktop.swingx.JXTextField batchNoTxt;
    private org.jdesktop.swingx.JXLabel closeBtn;
    private org.jdesktop.swingx.JXTextField coloutTxt;
    private org.jdesktop.swingx.JXLabel iteNamelbl;
    private org.jdesktop.swingx.JXLabel itemCodelbl;
    private org.jdesktop.swingx.JXLabel itemCodelbl1;
    private org.jdesktop.swingx.JXLabel itemCodelbl2;
    private org.jdesktop.swingx.JXLabel itemCodelbl3;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXTextField modelNameTxt;
    private org.jdesktop.swingx.JXTextField modelNoTxt;
    private org.jdesktop.swingx.JXLabel saveBtn;
    private org.jdesktop.swingx.JXPanel titlePanel;
    private org.jdesktop.swingx.JXPanel updateMobileIEMInobackPanel;
    // End of variables declaration//GEN-END:variables
    private String backUpIMEI = null;
}
