/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.CustomerController;
import com.project.mobileshop.core.dto.CustomerDTO;
import com.project.mobileshop.util.Validation;
import java.awt.Color;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Janitha Dhananjaya
 */
public class EditCustomerDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditCustomerDialog
     */
    public EditCustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0.6f));
    }
    
    public void getInfo(CustomerDTO customerDTO){
        custmerIdTxt.setText(customerDTO.getCustomerId());
        customerNameTxt.setText(customerDTO.getCustomerName());
        contactNoTxt.setText(String.valueOf(customerDTO.getContactNo()));
        NICnoTxt.setText(customerDTO.getNICno());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelbl = new org.jdesktop.swingx.JXPanel();
        closeBtn = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        customerIdlbl = new org.jdesktop.swingx.JXLabel();
        contactNolbl = new org.jdesktop.swingx.JXLabel();
        custmerIdTxt = new org.jdesktop.swingx.JXTextField();
        contactNoTxt = new org.jdesktop.swingx.JXTextField();
        NICnolbl = new org.jdesktop.swingx.JXLabel();
        customerNmaelbl = new org.jdesktop.swingx.JXLabel();
        customerNameTxt = new org.jdesktop.swingx.JXTextField();
        NICnoTxt = new org.jdesktop.swingx.JXTextField();
        saveChangesBtn = new org.jdesktop.swingx.JXLabel();
        backGroundlbl = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl.setOpaque(false);
        titlelbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        titlelbl.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 40, 30));

        jXLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("Edit Customer");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        titlelbl.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 180, 30));

        jXLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/GRn Item Title Bar.jpg"))); // NOI18N
        titlelbl.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        getContentPane().add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 720, 50));

        customerIdlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerIdlbl.setText("Customer ID");
        customerIdlbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        getContentPane().add(customerIdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 120, 30));

        contactNolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactNolbl.setText("Contact No");
        contactNolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        getContentPane().add(contactNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, 30));

        custmerIdTxt.setEditable(false);
        custmerIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        custmerIdTxt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        custmerIdTxt.setOpaque(false);
        custmerIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custmerIdTxtActionPerformed(evt);
            }
        });
        getContentPane().add(custmerIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 170, 30));

        contactNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        contactNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        contactNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTxtActionPerformed(evt);
            }
        });
        contactNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNoTxtKeyTyped(evt);
            }
        });
        getContentPane().add(contactNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 170, 30));

        NICnolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NICnolbl.setText("NIC No");
        NICnolbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        getContentPane().add(NICnolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 90, 30));

        customerNmaelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerNmaelbl.setText("Customer Name");
        customerNmaelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        getContentPane().add(customerNmaelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 160, 30));

        customerNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        customerNameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        customerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTxtActionPerformed(evt);
            }
        });
        customerNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerNameTxtKeyTyped(evt);
            }
        });
        getContentPane().add(customerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 170, 30));

        NICnoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        NICnoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        NICnoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NICnoTxtKeyTyped(evt);
            }
        });
        getContentPane().add(NICnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 180, 30));

        saveChangesBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saveChangesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveChangesBtn.setText("Save Changes");
        saveChangesBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        saveChangesBtn.setOpaque(true);
        saveChangesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveChangesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveChangesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveChangesBtnMouseExited(evt);
            }
        });
        getContentPane().add(saveChangesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 140, 40));

        backGroundlbl.setBackground(new java.awt.Color(255, 255, 255));
        backGroundlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backGroundlbl.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        backGroundlbl.setOpaque(true);
        getContentPane().add(backGroundlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 720, 310));

        setBounds(0, 90, 1370, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTxtActionPerformed

    private void contactNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNoTxtActionPerformed

    private void custmerIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custmerIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custmerIdTxtActionPerformed

    private void customerNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNameTxtKeyTyped
        Validation.name(customerNameTxt);
    }//GEN-LAST:event_customerNameTxtKeyTyped

    private void contactNoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoTxtKeyTyped
          char keyChar = evt.getKeyChar();
        String IMEI = contactNoTxt.getText();
        if (!Character.isDigit(keyChar)) {
            evt.consume();
        }
        if(IMEI.length()>9){
             evt.consume();
        }
    }//GEN-LAST:event_contactNoTxtKeyTyped

    private void NICnoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICnoTxtKeyTyped
        Validation.NIC(NICnoTxt);
    }//GEN-LAST:event_NICnoTxtKeyTyped

    private void contactNoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoTxtKeyReleased
        Validation.phoneNumber(contactNoTxt);
    }//GEN-LAST:event_contactNoTxtKeyReleased

    private void saveChangesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveChangesBtnMouseClicked
        String custId = custmerIdTxt.getText();
        String custName = customerNameTxt.getText();
        int contNo=Integer.parseInt(contactNoTxt.getText());
        String NICNo = NICnoTxt.getText();
        CustomerDTO customerDTO=new CustomerDTO(custId, custName, contNo, NICNo);
        try {
            boolean isUpdated = CustomerController.update(customerDTO);
            if(isUpdated){
                //JOptionPane.showMessageDialog(this, "Saved Successfully");
                String content = "Saved Successfully";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }else{
               //JOptionPane.showMessageDialog(this, "Error");
                String content = "Not Saved";
                JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
                dialog.getContent(content);
            }
        } catch (Exception ex) {
            Logger.getLogger(EditCustomerDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_saveChangesBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption red.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);

    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/close for Joption.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        closeBtn.setIcon(imageIcon);
    }//GEN-LAST:event_closeBtnMouseExited

    private void saveChangesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveChangesBtnMouseExited
        saveChangesBtn.setBackground(new Color(255, 255, 255));
        saveChangesBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_saveChangesBtnMouseExited

    private void saveChangesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveChangesBtnMouseEntered
        saveChangesBtn.setBackground(new Color(23, 114, 81));
        saveChangesBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_saveChangesBtnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCustomerDialog dialog = new EditCustomerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextField NICnoTxt;
    private org.jdesktop.swingx.JXLabel NICnolbl;
    private org.jdesktop.swingx.JXLabel backGroundlbl;
    private org.jdesktop.swingx.JXLabel closeBtn;
    private org.jdesktop.swingx.JXTextField contactNoTxt;
    private org.jdesktop.swingx.JXLabel contactNolbl;
    private org.jdesktop.swingx.JXTextField custmerIdTxt;
    private org.jdesktop.swingx.JXLabel customerIdlbl;
    private org.jdesktop.swingx.JXTextField customerNameTxt;
    private org.jdesktop.swingx.JXLabel customerNmaelbl;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel saveChangesBtn;
    private org.jdesktop.swingx.JXPanel titlelbl;
    // End of variables declaration//GEN-END:variables
}
