/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.panels.AddGRN;
import com.project.mobileshop.panels.CustomerInfoPanel;
import com.project.mobileshop.panels.CustomerPanel;
import com.project.mobileshop.panels.InvoicePanel;
import com.project.mobileshop.panels.OrderPanel;
import com.project.mobileshop.panels.MobilePanel;
import com.project.mobileshop.panels.StockPanel;
import com.project.mobileshop.panels.SupplierPanel;
import com.project.mobileshop.panels.reportPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setSize(1366, 768);
        setDate();
        setTime();
        start();
    }

    private void setDate() {
        Date d1 = new Date();
        DateFormat df = DateFormat.getDateInstance(DateFormat.FULL, Locale.ROOT);
        String date = df.format(d1);
        date_lbl.setText(date);

    }

    private void setTime() {
        Timer t1 = new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d1 = new Date();
                SimpleDateFormat sf = new SimpleDateFormat("hh:mm:ss a");
                String time = sf.format(d1);
                time_lbl.setText(time);
            }
        });

        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        minimizeBt = new org.jdesktop.swingx.JXLabel();
        date_lbl = new org.jdesktop.swingx.JXLabel();
        time_lbl = new org.jdesktop.swingx.JXLabel();
        closeBtLabel = new org.jdesktop.swingx.JXLabel();
        settingsBtn = new org.jdesktop.swingx.JXLabel();
        dateTimeLbl = new org.jdesktop.swingx.JXLabel();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        GRNLogo = new org.jdesktop.swingx.JXLabel();
        GRNBt = new org.jdesktop.swingx.JXLabel();
        supplierBt = new org.jdesktop.swingx.JXLabel();
        supplierLogo = new org.jdesktop.swingx.JXLabel();
        customerLogo = new org.jdesktop.swingx.JXLabel();
        stockLogo = new org.jdesktop.swingx.JXLabel();
        stockBt = new org.jdesktop.swingx.JXLabel();
        reportLogo = new org.jdesktop.swingx.JXLabel();
        reportBt = new org.jdesktop.swingx.JXLabel();
        productBt = new org.jdesktop.swingx.JXLabel();
        productLogo = new org.jdesktop.swingx.JXLabel();
        orderLogo = new org.jdesktop.swingx.JXLabel();
        customerBt = new org.jdesktop.swingx.JXLabel();
        orderBt = new org.jdesktop.swingx.JXLabel();
        invoiceLogoLbl = new org.jdesktop.swingx.JXLabel();
        invoiceBtn = new org.jdesktop.swingx.JXLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        CustPanelMain = new org.jdesktop.swingx.JXPanel();
        homepageLbl = new org.jdesktop.swingx.JXLabel();
        jXPanel5 = new org.jdesktop.swingx.JXPanel();
        mano_name = new org.jdesktop.swingx.JXLabel();
        mano_logo = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        jXLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jXLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jXLabel3.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jXPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jXPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Minimize Window_50px.png"))); // NOI18N
        minimizeBt.setToolTipText("Minimize");
        minimizeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtMouseExited(evt);
            }
        });
        jXPanel4.add(minimizeBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 50));

        date_lbl.setForeground(new java.awt.Color(255, 153, 153));
        date_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_lbl.setText("Date");
        date_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jXPanel4.add(date_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 410, 40));

        time_lbl.setForeground(new java.awt.Color(255, 153, 153));
        time_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_lbl.setText("Time");
        time_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        time_lbl.setName(""); // NOI18N
        jXPanel4.add(time_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 300, 50));

        closeBtLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Close Window transparent.png"))); // NOI18N
        closeBtLabel.setToolTipText("Close");
        closeBtLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtLabelMouseExited(evt);
            }
        });
        jXPanel4.add(closeBtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 50, 50));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Settings_52px.png"))); // NOI18N
        settingsBtn.setToolTipText("Settings");
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });
        jXPanel4.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 60, 50));

        dateTimeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/date & time back.jpg"))); // NOI18N
        jXPanel4.add(dateTimeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        jXPanel2.add(jXPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        getContentPane().add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1060, 90));

        jXPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRNLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Purchase Order_52px.png"))); // NOI18N
        GRNLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GRNLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GRNLogoMouseExited(evt);
            }
        });
        jXPanel3.add(GRNLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 70));

        GRNBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        GRNBt.setForeground(new java.awt.Color(255, 255, 255));
        GRNBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GRNBt.setText("GRN");
        GRNBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        GRNBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GRNBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GRNBtMouseExited(evt);
            }
        });
        jXPanel3.add(GRNBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, 60));

        supplierBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        supplierBt.setForeground(new java.awt.Color(255, 255, 255));
        supplierBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierBt.setText("Supplier");
        supplierBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        supplierBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierBtMouseExited(evt);
            }
        });
        jXPanel3.add(supplierBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, 60));

        supplierLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Checked Truck_50px.png"))); // NOI18N
        supplierLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierLogoMouseExited(evt);
            }
        });
        jXPanel3.add(supplierLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 70));

        customerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/User_50px.png"))); // NOI18N
        customerLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerLogoMouseExited(evt);
            }
        });
        jXPanel3.add(customerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, 60));

        stockLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Sell Stock_50px.png"))); // NOI18N
        stockLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockLogoMouseExited(evt);
            }
        });
        jXPanel3.add(stockLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 60, 60));

        stockBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        stockBt.setForeground(new java.awt.Color(255, 255, 255));
        stockBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockBt.setText("Stock");
        stockBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        stockBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockBtMouseExited(evt);
            }
        });
        jXPanel3.add(stockBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 180, 60));

        reportLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Reports.png"))); // NOI18N
        reportLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportLogoMouseExited(evt);
            }
        });
        jXPanel3.add(reportLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        reportBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        reportBt.setForeground(new java.awt.Color(255, 255, 255));
        reportBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportBt.setText("Reports");
        reportBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        reportBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportBtMouseExited(evt);
            }
        });
        jXPanel3.add(reportBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 180, 60));

        productBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        productBt.setForeground(new java.awt.Color(255, 255, 255));
        productBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productBt.setText("Mobile");
        productBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        productBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productBtMouseExited(evt);
            }
        });
        jXPanel3.add(productBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, 60));

        productLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Touchscreen Smartphone_52px.png"))); // NOI18N
        productLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productLogoMouseExited(evt);
            }
        });
        jXPanel3.add(productLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 90));

        orderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Cash Register_52px.png"))); // NOI18N
        orderLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderLogoMouseExited(evt);
            }
        });
        jXPanel3.add(orderLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 70));

        customerBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        customerBt.setForeground(new java.awt.Color(255, 255, 255));
        customerBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerBt.setText("Customer");
        customerBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        customerBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerBtMouseExited(evt);
            }
        });
        jXPanel3.add(customerBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 180, 60));

        orderBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        orderBt.setForeground(new java.awt.Color(255, 255, 255));
        orderBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderBt.setText("Order");
        orderBt.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        orderBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderBtMouseExited(evt);
            }
        });
        jXPanel3.add(orderBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 180, 60));

        invoiceLogoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceLogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Invoice_50px.png"))); // NOI18N
        invoiceLogoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceLogoLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoiceLogoLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoiceLogoLblMouseExited(evt);
            }
        });
        jXPanel3.add(invoiceLogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 70, 80));

        invoiceBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        invoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        invoiceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceBtn.setText("Invoice");
        invoiceBtn.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        invoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoiceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoiceBtnMouseExited(evt);
            }
        });
        jXPanel3.add(invoiceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 180, 60));

        jXLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jXLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/button panel new.jpg"))); // NOI18N
        jXPanel3.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 680));

        getContentPane().add(jXPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 680));

        CustPanelMain.setBackground(new java.awt.Color(0, 0, 0));
        CustPanelMain.add(homepageLbl);

        getContentPane().add(CustPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 1060, 680));

        jXPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mano_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mano_name.setText("ano Moblies");
        mano_name.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        jXPanel5.add(mano_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 220, 60));

        mano_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Small lobo mano.png"))); // NOI18N
        jXPanel5.add(mano_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 70));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/logo back.jpg"))); // NOI18N
        jXPanel5.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 90));

        getContentPane().add(jXPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtMouseClicked

        CustomerInfoPanel customerPanel = new CustomerInfoPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(customerPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_customerBtMouseClicked

    private void orderBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtMouseClicked

        OrderPanel orderPanel = new OrderPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(orderPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_orderBtMouseClicked

    private void supplierBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtMouseClicked

        SupplierPanel supplier = new SupplierPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(supplier);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_supplierBtMouseClicked

    private void GRNBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNBtMouseClicked
        AddGRN grn = new AddGRN();
        CustPanelMain.removeAll();
        CustPanelMain.add(grn);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_GRNBtMouseClicked

    private void productBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtMouseClicked

        MobilePanel productPanel = new MobilePanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(productPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);

    }//GEN-LAST:event_productBtMouseClicked

    private void stockBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtMouseClicked

        StockPanel stockPanel = new StockPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(stockPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_stockBtMouseClicked

    private void orderBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Order Logo.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        orderLogo.setIcon(imageIcon);
        orderBt.setFont(new Font("Lucida Bright", 1, 38));
        orderBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_orderBtMouseEntered

    private void orderBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Cash Register_52px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        orderLogo.setIcon(imageIcon);
        orderBt.setFont(new Font("Lucida Bright", 1, 30));
        orderBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_orderBtMouseExited

    private void orderLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogoMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Cash Register_52px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        orderLogo.setIcon(imageIcon);
        orderBt.setFont(new Font("Lucida Bright", 1, 30));
        orderBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_orderLogoMouseExited

    private void orderLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Order Logo.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        orderLogo.setIcon(imageIcon);
        orderBt.setFont(new Font("Lucida Bright", 1, 34));
        orderBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_orderLogoMouseEntered

    private void closeBtLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtLabelMouseClicked
        JoptionPaneClosingDialog closingDialog = new JoptionPaneClosingDialog(this, true);
        String content = "Do you want to exit?";
        closingDialog.getContent(content);

    }//GEN-LAST:event_closeBtLabelMouseClicked

    private void minimizeBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeBtMouseClicked

    private void customerBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/customer logo.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        customerLogo.setIcon(imageIcon);
        customerBt.setFont(new Font("Lucida Bright", 1, 34));
        customerBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_customerBtMouseEntered

    private void customerLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/customer logo.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        customerLogo.setIcon(imageIcon);
        customerBt.setFont(new Font("Lucida Bright", 1, 34));
        customerBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_customerLogoMouseEntered

    private void customerBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/User_50px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        customerLogo.setIcon(imageIcon);
        customerBt.setFont(new Font("Lucida Bright", 1, 30));
        customerBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_customerBtMouseExited

    private void customerLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLogoMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/User_50px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        customerLogo.setIcon(imageIcon);
        customerBt.setFont(new Font("Lucida Bright", 1, 30));
        customerBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_customerLogoMouseExited

    private void GRNBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/GRN.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        GRNLogo.setIcon(imageIcon);
        GRNBt.setFont(new Font("Lucida Bright", 1, 34));
        GRNBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_GRNBtMouseEntered

    private void GRNLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/GRN.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        GRNLogo.setIcon(imageIcon);
        GRNBt.setFont(new Font("Lucida Bright", 1, 34));
        GRNBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_GRNLogoMouseEntered

    private void GRNBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Purchase Order_52px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        GRNLogo.setIcon(imageIcon);
        GRNBt.setFont(new Font("Lucida Bright", 1, 30));
        GRNBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GRNBtMouseExited

    private void GRNLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNLogoMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Purchase Order_52px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        GRNLogo.setIcon(imageIcon);
        GRNBt.setFont(new Font("Lucida Bright", 1, 30));
        GRNBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GRNLogoMouseExited

    private void supplierBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Supplier Logo.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        supplierLogo.setIcon(imageIcon);
        supplierBt.setFont(new Font("Lucida Bright", 1, 34));
        supplierBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_supplierBtMouseEntered

    private void supplierLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Supplier Logo.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        supplierLogo.setIcon(imageIcon);
        supplierBt.setFont(new Font("Lucida Bright", 1, 30));
        supplierBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_supplierLogoMouseEntered

    private void supplierBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Checked Truck_50px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        supplierLogo.setIcon(imageIcon);
        supplierBt.setFont(new Font("Lucida Bright", 1, 30));
        supplierBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_supplierBtMouseExited

    private void supplierLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLogoMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Checked Truck_50px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        supplierLogo.setIcon(imageIcon);
        supplierBt.setFont(new Font("Lucida Bright", 1, 30));
        supplierBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_supplierLogoMouseExited

    private void closeBtLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtLabelMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Close Window red.png");
        ImageIcon icon = new ImageIcon(resource);
        closeBtLabel.setIcon(icon);
    }//GEN-LAST:event_closeBtLabelMouseEntered

    private void closeBtLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtLabelMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Close Window transparent.png");
        ImageIcon icon = new ImageIcon(resource);
        closeBtLabel.setIcon(icon);
    }//GEN-LAST:event_closeBtLabelMouseExited

    private void minimizeBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Minimize Window_48px_2.png");
        ImageIcon icon = new ImageIcon(resource);
        minimizeBt.setIcon(icon);
    }//GEN-LAST:event_minimizeBtMouseEntered

    private void minimizeBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Minimize Window_50px.png");
        ImageIcon icon = new ImageIcon(resource);
        minimizeBt.setIcon(icon);
    }//GEN-LAST:event_minimizeBtMouseExited

    private void productLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/moblie white.png");
        ImageIcon icon = new ImageIcon(resource);
        productLogo.setIcon(icon);
        productBt.setFont(new Font("Lucida Bright", 1, 34));
        productBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_productLogoMouseEntered

    private void productBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/moblie white.png");
        ImageIcon icon = new ImageIcon(resource);
        productLogo.setIcon(icon);
        productBt.setFont(new Font("Lucida Bright", 1, 34));
        productBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_productBtMouseEntered

    private void productLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLogoMouseExited

        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Touchscreen Smartphone_52px.png");
        ImageIcon icon = new ImageIcon(resource);
        productLogo.setIcon(icon);
        productBt.setFont(new Font("Lucida Bright", 1, 30));
        productBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_productLogoMouseExited

    private void productBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Touchscreen Smartphone_52px.png");
        ImageIcon icon = new ImageIcon(resource);
        productLogo.setIcon(icon);
        productBt.setFont(new Font("Lucida Bright", 1, 30));
        productBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_productBtMouseExited

    private void stockLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/stock large.png");
        ImageIcon icon = new ImageIcon(resource);
        stockLogo.setIcon(icon);
        stockBt.setFont(new Font("", 1, 34));
        stockBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_stockLogoMouseEntered

    private void stockBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/stock large.png");
        ImageIcon icon = new ImageIcon(resource);
        stockLogo.setIcon(icon);
        stockBt.setFont(new Font("Lucida Bright", 1, 34));
        stockBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_stockBtMouseEntered

    private void stockLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockLogoMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Sell Stock_50px.png");
        ImageIcon icon = new ImageIcon(resource);
        stockLogo.setIcon(icon);
        stockBt.setFont(new Font("Lucida Bright", 1, 30));
        stockBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_stockLogoMouseExited

    private void stockBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Sell Stock_50px.png");
        ImageIcon icon = new ImageIcon(resource);
        stockLogo.setIcon(icon);
        stockBt.setFont(new Font("Lucida Bright", 1, 30));
        stockBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_stockBtMouseExited

    private void reportLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLogoMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Report large.png");
        ImageIcon icon = new ImageIcon(resource);
        reportLogo.setIcon(icon);
        reportBt.setFont(new Font("Lucida Bright", 1, 34));
        reportBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_reportLogoMouseEntered

    private void reportBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Report large.png");
        ImageIcon icon = new ImageIcon(resource);
        reportLogo.setIcon(icon);
        reportBt.setFont(new Font("Lucida Bright", 1, 34));
        reportBt.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_reportBtMouseEntered

    private void reportLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLogoMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Reports.png");
        ImageIcon icon = new ImageIcon(resource);
        reportLogo.setIcon(icon);
        reportBt.setFont(new Font("Lucida Bright", 1, 30));
        reportBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_reportLogoMouseExited

    private void reportBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Reports.png");
        ImageIcon icon = new ImageIcon(resource);
        reportLogo.setIcon(icon);
        reportBt.setFont(new Font("Lucida Bright", 1, 30));
        reportBt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_reportBtMouseExited

    private void orderLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogoMouseClicked
        OrderPanel orderPanel = new OrderPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(orderPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_orderLogoMouseClicked

    private void customerLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLogoMouseClicked

        CustomerPanel customerPanel = new CustomerPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(customerPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_customerLogoMouseClicked

    private void GRNLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNLogoMouseClicked

        AddGRN grn = new AddGRN();
        CustPanelMain.removeAll();
        CustPanelMain.add(grn);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_GRNLogoMouseClicked

    private void supplierLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLogoMouseClicked

        SupplierPanel supplier = new SupplierPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(supplier);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_supplierLogoMouseClicked

    private void productLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLogoMouseClicked

        MobilePanel productPanel = new MobilePanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(productPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_productLogoMouseClicked

    private void stockLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockLogoMouseClicked

        StockPanel stockPanel = new StockPanel();
        CustPanelMain.removeAll();
        CustPanelMain.add(stockPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_stockLogoMouseClicked

    private void reportBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtMouseClicked
        reportPanel p = new reportPanel();

        CustPanelMain.removeAll();
        CustPanelMain.add(p);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_reportBtMouseClicked

    private void reportLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLogoMouseClicked
        reportPanel p = new reportPanel();

        CustPanelMain.removeAll();
        CustPanelMain.add(p);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_reportLogoMouseClicked

    private void invoiceLogoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceLogoLblMouseClicked
        InvoicePanel invPanel = new InvoicePanel();

        CustPanelMain.removeAll();
        CustPanelMain.add(invPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_invoiceLogoLblMouseClicked

    private void invoiceLogoLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceLogoLblMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/invoice.png");
        ImageIcon icon = new ImageIcon(resource);
        invoiceLogoLbl.setIcon(icon);
        invoiceBtn.setFont(new Font("Lucida Bright", 1, 34));
        invoiceLogoLbl.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_invoiceLogoLblMouseEntered

    private void invoiceLogoLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceLogoLblMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Invoice_50px.png");
        ImageIcon icon = new ImageIcon(resource);
        invoiceLogoLbl.setIcon(icon);
        invoiceBtn.setFont(new Font("Lucida Bright", 1, 30));
        invoiceLogoLbl.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_invoiceLogoLblMouseExited

    private void invoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceBtnMouseClicked
        InvoicePanel invPanel = new InvoicePanel();

        CustPanelMain.removeAll();
        CustPanelMain.add(invPanel);
        CustPanelMain.repaint();
        CustPanelMain.revalidate();
        CustPanelMain.setVisible(true);
    }//GEN-LAST:event_invoiceBtnMouseClicked

    private void invoiceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceBtnMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/invoice.png");
        ImageIcon icon = new ImageIcon(resource);
        invoiceLogoLbl.setIcon(icon);
        invoiceBtn.setFont(new Font("Lucida Bright", 1, 34));
        invoiceBtn.setForeground(new Color(255, 153, 0));
    }//GEN-LAST:event_invoiceBtnMouseEntered

    private void invoiceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceBtnMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Invoice_50px.png");
        ImageIcon icon = new ImageIcon(resource);
        invoiceLogoLbl.setIcon(icon);
        invoiceBtn.setFont(new Font("Lucida Bright", 1, 30));
        invoiceBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_invoiceBtnMouseExited

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Settings_52px_1.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        settingsBtn.setIcon(imageIcon);

    }//GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/Settings_52px.png");
        ImageIcon imageIcon = new ImageIcon(resource);
        settingsBtn.setIcon(imageIcon);
    }//GEN-LAST:event_settingsBtnMouseExited

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        SettingsFrame frame = new SettingsFrame();
        frame.setVisible(true);

    }//GEN-LAST:event_settingsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    public JXPanel getMainPanel() {
        return CustPanelMain;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXPanel CustPanelMain;
    private org.jdesktop.swingx.JXLabel GRNBt;
    private org.jdesktop.swingx.JXLabel GRNLogo;
    private org.jdesktop.swingx.JXLabel closeBtLabel;
    private org.jdesktop.swingx.JXLabel customerBt;
    private org.jdesktop.swingx.JXLabel customerLogo;
    private org.jdesktop.swingx.JXLabel dateTimeLbl;
    private org.jdesktop.swingx.JXLabel date_lbl;
    private org.jdesktop.swingx.JXLabel homepageLbl;
    private org.jdesktop.swingx.JXLabel invoiceBtn;
    private org.jdesktop.swingx.JXLabel invoiceLogoLbl;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private org.jdesktop.swingx.JXPanel jXPanel5;
    private org.jdesktop.swingx.JXLabel mano_logo;
    private org.jdesktop.swingx.JXLabel mano_name;
    private org.jdesktop.swingx.JXLabel minimizeBt;
    private org.jdesktop.swingx.JXLabel orderBt;
    private org.jdesktop.swingx.JXLabel orderLogo;
    private org.jdesktop.swingx.JXLabel productBt;
    private org.jdesktop.swingx.JXLabel productLogo;
    private org.jdesktop.swingx.JXLabel reportBt;
    private org.jdesktop.swingx.JXLabel reportLogo;
    private org.jdesktop.swingx.JXLabel settingsBtn;
    private org.jdesktop.swingx.JXLabel stockBt;
    private org.jdesktop.swingx.JXLabel stockLogo;
    private org.jdesktop.swingx.JXLabel supplierBt;
    private org.jdesktop.swingx.JXLabel supplierLogo;
    private org.jdesktop.swingx.JXLabel time_lbl;
    // End of variables declaration//GEN-END:variables

    private void start() {
        Random number = new Random();
        int no = number.nextInt(5);
        System.out.println("no :" + no);
        switch (no) {
            case 1:
                GalaxyS5();
                return;
            case 2:
                Note8_One();
                return;
            case 3:
                Note8_Two();
                return;
            case 4:
                GalaxyS5();
                return;
            case 5:
                Note8_Two();
            default:
                GalaxyS5();
                return;

        }

    }

    private void GalaxyS5() {
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/home bachground.jpg");
        ImageIcon imageIcon = new ImageIcon(resource);
        homepageLbl.setIcon(imageIcon);
    }

    private void Note8_One() {
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/NEW.jpg");
        ImageIcon imageIcon = new ImageIcon(resource);
        homepageLbl.setIcon(imageIcon);
    }

    private void Note8_Two() {
        URL resource = this.getClass().getResource("/com/project/mobileshop/images/Images/NOTE 8 2.jpg");
        ImageIcon imageIcon = new ImageIcon(resource);
        homepageLbl.setIcon(imageIcon);
    }
}
