/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.MobileDetailController;
import com.project.mobileshop.core.dto.MobileDTO;
import com.project.mobileshop.core.dto.MobileDetailDTO;
import com.project.mobileshop.core.dto.ModelDTO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class StockMoreDetailDialog extends javax.swing.JDialog {

    /**
     * Creates new form StockMoreDetailDialog
     */
    public StockMoreDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0.6f));
    }

    public void moreDetails(ModelDTO modelDTO) throws Exception {
        brandTxt.setText(modelDTO.getBrand());
        modelnameTxt.setText(modelDTO.getModelName());
        String modelNo = modelDTO.getModelNo();
        modelNoTxt.setText(modelNo);

        ArrayList<MobileDetailDTO> mobileInfoList = MobileDetailController.getMobileDetails(modelNo);
        DefaultTableModel dtm = (DefaultTableModel) mobileDetailtable.getModel();

        for (MobileDetailDTO m : mobileInfoList) {
            Object[] row = {m.getIMEIno(),
                m.getColur(),
                m.getStatus(),
                m.getBatchNo(),
                m.getGRNno()};
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moreDetailDialogPaneel = new org.jdesktop.swingx.JXPanel();
        titlePanel = new org.jdesktop.swingx.JXPanel();
        titlelbl = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        itemCodelbl = new org.jdesktop.swingx.JXLabel();
        mobiletable = new javax.swing.JScrollPane();
        mobileDetailtable = new org.jdesktop.swingx.JXTable();
        OKbt = new org.jdesktop.swingx.JXLabel();
        itemNamelbl = new org.jdesktop.swingx.JXLabel();
        brandTxt = new org.jdesktop.swingx.JXTextField();
        modelNoTxt = new org.jdesktop.swingx.JXTextField();
        itemNamelbl1 = new org.jdesktop.swingx.JXLabel();
        modelnameTxt = new org.jdesktop.swingx.JXTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moreDetailDialogPaneel.setBackground(new java.awt.Color(255, 255, 255));
        moreDetailDialogPaneel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        moreDetailDialogPaneel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setOpaque(false);
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelbl.setText("Mobile Details");
        titlelbl.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        titlePanel.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 180, 30));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/date & time back.jpg"))); // NOI18N
        titlePanel.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 800, 50));

        moreDetailDialogPaneel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        itemCodelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl.setText("Brand");
        itemCodelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        moreDetailDialogPaneel.add(itemCodelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        mobileDetailtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IMEI No", "Colour", "Status", "Batch No", "GRN No"
            }
        ));
        mobileDetailtable.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        mobileDetailtable.setGridColor(new java.awt.Color(0, 0, 0));
        mobiletable.setViewportView(mobileDetailtable);

        moreDetailDialogPaneel.add(mobiletable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 630, 320));

        OKbt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OKbt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OKbt.setText("OK");
        OKbt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        OKbt.setOpaque(true);
        OKbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKbtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OKbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OKbtMouseExited(evt);
            }
        });
        moreDetailDialogPaneel.add(OKbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 90, 30));

        itemNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNamelbl.setText("Model No");
        itemNamelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        moreDetailDialogPaneel.add(itemNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, 30));

        brandTxt.setEditable(false);
        brandTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        brandTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        brandTxt.setOpaque(false);
        brandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTxtActionPerformed(evt);
            }
        });
        moreDetailDialogPaneel.add(brandTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 30));

        modelNoTxt.setEditable(false);
        modelNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNoTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelNoTxt.setOpaque(false);
        modelNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxtActionPerformed(evt);
            }
        });
        moreDetailDialogPaneel.add(modelNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 110, 30));

        itemNamelbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNamelbl1.setText("Model Name");
        itemNamelbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        moreDetailDialogPaneel.add(itemNamelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, 30));

        modelnameTxt.setEditable(false);
        modelnameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelnameTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        modelnameTxt.setOpaque(false);
        modelnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelnameTxtActionPerformed(evt);
            }
        });
        moreDetailDialogPaneel.add(modelnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 140, 30));

        getContentPane().add(moreDetailDialogPaneel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, 520));

        setBounds(0, 90, 1370, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void OKbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKbtMouseClicked
        dispose();
    }//GEN-LAST:event_OKbtMouseClicked

    private void brandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTxtActionPerformed

    private void modelNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNoTxtActionPerformed

    private void modelnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelnameTxtActionPerformed

    private void OKbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKbtMouseEntered
        OKbt.setBackground(new Color(23, 114, 81));
        OKbt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_OKbtMouseEntered

    private void OKbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKbtMouseExited
        OKbt.setBackground(new Color(255, 255, 255));
        OKbt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_OKbtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockMoreDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockMoreDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockMoreDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockMoreDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StockMoreDetailDialog dialog = new StockMoreDetailDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel OKbt;
    private org.jdesktop.swingx.JXTextField brandTxt;
    private org.jdesktop.swingx.JXLabel itemCodelbl;
    private org.jdesktop.swingx.JXLabel itemNamelbl;
    private org.jdesktop.swingx.JXLabel itemNamelbl1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXTable mobileDetailtable;
    private javax.swing.JScrollPane mobiletable;
    private org.jdesktop.swingx.JXTextField modelNoTxt;
    private org.jdesktop.swingx.JXTextField modelnameTxt;
    private org.jdesktop.swingx.JXPanel moreDetailDialogPaneel;
    private org.jdesktop.swingx.JXPanel titlePanel;
    private org.jdesktop.swingx.JXLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
