/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.BatchController;
import com.project.mobileshop.controller.ModelController;
import com.project.mobileshop.core.dto.BatchDTO;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class stockBatchDetailsDialog extends javax.swing.JDialog {

    /**
     * Creates new form stockBatchDetailsDialog
     */
    public stockBatchDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0.7f));
    }

    public void setBatchNos(BatchDTO batchDTO, String modelName) throws Exception {
        System.out.println("model No in dialog box  " + batchDTO.getModelNo());
        ArrayList<BatchDTO> all = BatchController.searchBatch(batchDTO);
        if (all != null) {
            for (BatchDTO a : all) {
                String batch = a.getBatchNo();

                modelNmeTxt.setText(modelName);
                batchNoComboBox.addItem(batch);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new org.jdesktop.swingx.JXPanel();
        titlelbl1 = new org.jdesktop.swingx.JXLabel();
        titlelbl = new org.jdesktop.swingx.JXLabel();
        mobileDetailsPanel = new org.jdesktop.swingx.JXPanel();
        itemCodelbl = new org.jdesktop.swingx.JXLabel();
        batchNoComboBox = new org.jdesktop.swingx.JXComboBox();
        itemCodelbl1 = new org.jdesktop.swingx.JXLabel();
        itemCodelbl2 = new org.jdesktop.swingx.JXLabel();
        itemCodelbl3 = new org.jdesktop.swingx.JXLabel();
        itemCodelbl4 = new org.jdesktop.swingx.JXLabel();
        deliverdPriceTxt = new org.jdesktop.swingx.JXTextField();
        OKbt = new org.jdesktop.swingx.JXLabel();
        qtyOnHandTxt = new org.jdesktop.swingx.JXTextField();
        spendAmountTxt = new org.jdesktop.swingx.JXTextField();
        SellingPriceTxt = new org.jdesktop.swingx.JXTextField();
        itemNamelbl = new org.jdesktop.swingx.JXLabel();
        modelNmeTxt = new org.jdesktop.swingx.JXTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(102, 0, 102));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl1.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelbl1.setText("Batch Details");
        titlelbl1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        titlePanel.add(titlelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 180, 30));

        titlelbl.setForeground(new java.awt.Color(255, 255, 255));
        titlelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/date & time back.jpg"))); // NOI18N
        titlelbl.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        titlePanel.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 720, 50));

        mobileDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        itemCodelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl.setText("Batch No");
        itemCodelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        batchNoComboBox.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        batchNoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchNoComboBoxItemStateChanged(evt);
            }
        });
        batchNoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNoComboBoxActionPerformed(evt);
            }
        });

        itemCodelbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl1.setText("Deliverd Price");
        itemCodelbl1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        itemCodelbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl2.setText("Spend Amount");
        itemCodelbl2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        itemCodelbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl3.setText("Selling Price");
        itemCodelbl3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        itemCodelbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemCodelbl4.setText("Qty On Hand");
        itemCodelbl4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        deliverdPriceTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        deliverdPriceTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        deliverdPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverdPriceTxtActionPerformed(evt);
            }
        });

        OKbt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OKbt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OKbt.setText("OK");
        OKbt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        OKbt.setOpaque(true);
        OKbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKbtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OKbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OKbtMouseExited(evt);
            }
        });

        qtyOnHandTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        qtyOnHandTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        spendAmountTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        spendAmountTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        SellingPriceTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        SellingPriceTxt.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        itemNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNamelbl.setText("Model Name");
        itemNamelbl.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N

        modelNmeTxt.setEditable(false);
        modelNmeTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        modelNmeTxt.setAlignmentX(1.5F);
        modelNmeTxt.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        modelNmeTxt.setOpaque(false);
        modelNmeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNmeTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mobileDetailsPanelLayout = new javax.swing.GroupLayout(mobileDetailsPanel);
        mobileDetailsPanel.setLayout(mobileDetailsPanelLayout);
        mobileDetailsPanelLayout.setHorizontalGroup(
            mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(itemCodelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deliverdPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(itemCodelbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyOnHandTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(53, 53, 53)))
                .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemCodelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCodelbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SellingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spendAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mobileDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemCodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(batchNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelNmeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(OKbt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mobileDetailsPanelLayout.setVerticalGroup(
            mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemCodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(batchNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itemNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modelNmeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                        .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deliverdPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCodelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCodelbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mobileDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qtyOnHandTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemCodelbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(itemCodelbl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mobileDetailsPanelLayout.createSequentialGroup()
                        .addComponent(SellingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(spendAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(OKbt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(mobileDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 720, 380));

        setBounds(0, 90, 1370, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void OKbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKbtMouseClicked
        dispose();
    }//GEN-LAST:event_OKbtMouseClicked

    private void modelNmeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNmeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNmeTxtActionPerformed

    private void batchNoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchNoComboBoxItemStateChanged
        String batchNo = batchNoComboBox.getSelectedItem().toString();
        BatchDTO batchDTO = new BatchDTO();
        batchDTO.setBatchNo(batchNo);
        try {
            BatchDTO b = BatchController.getSelectedBatchDetails(batchNo);
            if (b != null) {
                spendAmountTxt.setText(String.valueOf(b.getAmount()));
                deliverdPriceTxt.setText(String.valueOf(b.getOriginalPrice()));
                SellingPriceTxt.setText(String.valueOf(b.getSellingPrice()));
                qtyOnHandTxt.setText(String.valueOf(b.getQty()));

            } else {
                JOptionPane.showMessageDialog(this, "No suitable details for this batch no");
            }

        } catch (Exception ex) {
            Logger.getLogger(stockBatchDetailsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_batchNoComboBoxItemStateChanged

    private void batchNoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNoComboBoxActionPerformed

    private void deliverdPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverdPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverdPriceTxtActionPerformed

    private void OKbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKbtMouseExited
        OKbt.setBackground(new Color(255, 255, 255));
        OKbt.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_OKbtMouseExited

    private void OKbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKbtMouseEntered
        OKbt.setBackground(new Color(23, 114, 81));
        OKbt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_OKbtMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockBatchDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockBatchDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockBatchDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockBatchDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stockBatchDetailsDialog dialog = new stockBatchDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel OKbt;
    private org.jdesktop.swingx.JXTextField SellingPriceTxt;
    private org.jdesktop.swingx.JXComboBox batchNoComboBox;
    private org.jdesktop.swingx.JXTextField deliverdPriceTxt;
    private org.jdesktop.swingx.JXLabel itemCodelbl;
    private org.jdesktop.swingx.JXLabel itemCodelbl1;
    private org.jdesktop.swingx.JXLabel itemCodelbl2;
    private org.jdesktop.swingx.JXLabel itemCodelbl3;
    private org.jdesktop.swingx.JXLabel itemCodelbl4;
    private org.jdesktop.swingx.JXLabel itemNamelbl;
    private org.jdesktop.swingx.JXPanel mobileDetailsPanel;
    private org.jdesktop.swingx.JXTextField modelNmeTxt;
    private org.jdesktop.swingx.JXTextField qtyOnHandTxt;
    private org.jdesktop.swingx.JXTextField spendAmountTxt;
    private org.jdesktop.swingx.JXPanel titlePanel;
    private org.jdesktop.swingx.JXLabel titlelbl;
    private org.jdesktop.swingx.JXLabel titlelbl1;
    // End of variables declaration//GEN-END:variables
}
