/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.mobileshop.view;

import com.project.mobileshop.controller.GRNController;
import com.project.mobileshop.core.dto.GRNDTO;
import com.project.mobileshop.util.Validation;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janitha Dhananjaya
 */
public class ViewGRNs extends javax.swing.JDialog {

    /**
     * Creates new form ViewGRNs
     */
    public ViewGRNs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        LoadAllGRNs();
        DisabledDates();
    }

    private void DisabledDates() {
        Date date = new Date();
        GRN_DatePicker.getMonthView().setUpperBound(date);
    }
    
    public void LoadAllGRNs() {
        try {
            ArrayList<GRNDTO> grnList = GRNController.getAllGRNs();
            DefaultTableModel dtm = (DefaultTableModel) viewAllGrnTable.getModel();
            dtm.setRowCount(0);
            for (GRNDTO g : grnList) {
                Object[] row = {g.getGRNId(), g.getGRNDate(), g.getSupplierId(), g.getTotalAmount()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewGRNs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroungLabel = new org.jdesktop.swingx.JXLabel();
        GRNPanel = new org.jdesktop.swingx.JXPanel();
        GRNPanel1 = new org.jdesktop.swingx.JXPanel();
        GRN_DatePicker = new org.jdesktop.swingx.JXDatePicker();
        title_lbl = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewAllGrnTable = new org.jdesktop.swingx.JXTable();
        GRNIDTxt = new org.jdesktop.swingx.JXSearchField();
        supplierNameTxt = new org.jdesktop.swingx.JXSearchField();
        CompanyTxt = new org.jdesktop.swingx.JXSearchField();
        itemDetailsBtn = new org.jdesktop.swingx.JXLabel();
        backBtn = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();

        backgroungLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/mobileshop/images/Images/Blur background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        GRNPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRNPanel1.setBackground(new java.awt.Color(255, 255, 255));
        GRNPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRN_DatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRN_DatePickerActionPerformed(evt);
            }
        });
        GRNPanel1.add(GRN_DatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 210, 30));

        title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lbl.setText("View All");
        title_lbl.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        GRNPanel1.add(title_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 270, 50));

        viewAllGrnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "GRN No", "Date", "Supplier ID", "Total Amount"
            }
        ));
        viewAllGrnTable.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        viewAllGrnTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(viewAllGrnTable);

        GRNPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 920, 240));

        GRNIDTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        GRNIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRNIDTxtActionPerformed(evt);
            }
        });
        GRNPanel1.add(GRNIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 190, 30));

        supplierNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        supplierNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtActionPerformed(evt);
            }
        });
        supplierNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                supplierNameTxtKeyTyped(evt);
            }
        });
        GRNPanel1.add(supplierNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 210, 30));

        CompanyTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        CompanyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyTxtActionPerformed(evt);
            }
        });
        GRNPanel1.add(CompanyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 190, 30));

        itemDetailsBtn.setBackground(new java.awt.Color(255, 255, 255));
        itemDetailsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemDetailsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemDetailsBtn.setText("Item Details");
        itemDetailsBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        itemDetailsBtn.setOpaque(true);
        itemDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDetailsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemDetailsBtnMouseExited(evt);
            }
        });
        GRNPanel1.add(itemDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, 140, 40));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("Back");
        backBtn.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        backBtn.setOpaque(true);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        GRNPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 120, 40));

        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel1.setText("Company");
        jXLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 140, 30));

        jXLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel2.setText("Date");
        jXLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 30));

        jXLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel3.setText("Supplier Name");
        jXLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 30));

        jXLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabel4.setText("GRN No");
        jXLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        GRNPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 140, 30));

        jXLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Search From", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 1, 14))); // NOI18N
        GRNPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 930, 160));

        GRNPanel.add(GRNPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GRNPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GRNPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBounds(310, 90, 1060, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void GRN_DatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRN_DatePickerActionPerformed
        Date date = GRN_DatePicker.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String Date = dateFormat.format(date);

        try {
            ArrayList<GRNDTO> grnList = GRNController.getSelectedGRNFromDate(Date);
            if (grnList != null) {
                DefaultTableModel dtm = (DefaultTableModel) viewAllGrnTable.getModel();
                dtm.setRowCount(0);
                for (GRNDTO g : grnList) {
                    Object[] row = {g.getGRNId(), g.getGRNDate(), g.getSupplierId(), g.getTotalAmount()};
                    dtm.addRow(row);
                    System.out.println("sdbhhsdghgh");
                }
                System.out.println("nulllll");
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewGRNs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GRN_DatePickerActionPerformed

    private void itemDetailsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDetailsBtnMouseClicked
        if (viewAllGrnTable.getSelectedRow() == -1) {
            //JOptionPane.showMessageDialog(this, "Select a GRN No");
            String content = "Select a GRN No";
            JoptionMessageDialog dialog = new JoptionMessageDialog(null, true);
            dialog.getContent(content);
            return;
        }

        int selectedRow = viewAllGrnTable.getSelectedRow();
        String GRNno = viewAllGrnTable.getValueAt(selectedRow, 0).toString();
        String Date = viewAllGrnTable.getValueAt(selectedRow, 1).toString();
        String supplierID = viewAllGrnTable.getValueAt(selectedRow, 2).toString();
        double Amount = Double.parseDouble(viewAllGrnTable.getValueAt(selectedRow, 3).toString());

        GRNDTO grndto = new GRNDTO(GRNno, supplierID, Date, Amount);

        GRNItemDetailsDailog d = new GRNItemDetailsDailog(null, true);
        d.getGRN(grndto);
        d.setVisible(true);
    }//GEN-LAST:event_itemDetailsBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void GRNIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRNIDTxtActionPerformed
        String GRNID = GRNIDTxt.getText();
        try {
            GRNDTO result = GRNController.getSelectedGRNFromGRNId(GRNID);
            if (result != null) {
                DefaultTableModel dtm = (DefaultTableModel) viewAllGrnTable.getModel();
                dtm.setRowCount(0);
                Object[] row = {result.getGRNId(), result.getGRNDate(), result.getSupplierId(), result.getTotalAmount()};
                dtm.addRow(row);

            }
        } catch (Exception ex) {
            Logger.getLogger(ViewGRNs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GRNIDTxtActionPerformed

    private void supplierNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtActionPerformed
        String supplierName = supplierNameTxt.getText();
        try {
            ArrayList<GRNDTO> grnList = GRNController.getSelectedGRNFromSupplierName(supplierName);
            if (grnList != null) {
                DefaultTableModel dtm = (DefaultTableModel) viewAllGrnTable.getModel();
                dtm.setRowCount(0);
                for (GRNDTO g : grnList) {
                    Object[] row = {g.getGRNId(), g.getGRNDate(), g.getSupplierId(), g.getTotalAmount()};
                    dtm.addRow(row);

                }

            }
            System.out.println("null");
        } catch (Exception ex) {
            Logger.getLogger(ViewGRNs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supplierNameTxtActionPerformed

    private void CompanyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyTxtActionPerformed
        String company = CompanyTxt.getText();
        try {
            ArrayList<GRNDTO> grnList = GRNController.getSelectedGRNFromCompany(company);
            if (grnList != null) {
                DefaultTableModel dtm = (DefaultTableModel) viewAllGrnTable.getModel();
                dtm.setRowCount(0);
                for (GRNDTO g : grnList) {
                    Object[] row = {g.getGRNId(), g.getGRNDate(), g.getSupplierId(), g.getTotalAmount()};
                    dtm.addRow(row);

                }

            }
            System.out.println("null");
        } catch (Exception ex) {
            Logger.getLogger(ViewGRNs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CompanyTxtActionPerformed

    private void supplierNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameTxtKeyTyped
        Validation.name(supplierNameTxt);
    }//GEN-LAST:event_supplierNameTxtKeyTyped

    private void itemDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDetailsBtnMouseEntered
        itemDetailsBtn.setBackground(new Color(23, 114, 81));
        itemDetailsBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_itemDetailsBtnMouseEntered

    private void itemDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDetailsBtnMouseExited
        itemDetailsBtn.setBackground(new Color(255, 255, 255));
        itemDetailsBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_itemDetailsBtnMouseExited

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
         backBtn.setBackground(new Color(255, 14, 65));
        backBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 255, 255));
        backBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_backBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGRNs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGRNs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGRNs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGRNs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewGRNs dialog = new ViewGRNs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXSearchField CompanyTxt;
    private org.jdesktop.swingx.JXSearchField GRNIDTxt;
    private org.jdesktop.swingx.JXPanel GRNPanel;
    private org.jdesktop.swingx.JXPanel GRNPanel1;
    private org.jdesktop.swingx.JXDatePicker GRN_DatePicker;
    private org.jdesktop.swingx.JXLabel backBtn;
    private org.jdesktop.swingx.JXLabel backgroungLabel;
    private org.jdesktop.swingx.JXLabel itemDetailsBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXSearchField supplierNameTxt;
    private org.jdesktop.swingx.JXLabel title_lbl;
    private org.jdesktop.swingx.JXTable viewAllGrnTable;
    // End of variables declaration//GEN-END:variables
}
